# Copyright 2025 The go-taas Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"

run:
  timeout: 10m

linters:
  default: standard
  enable:
    - errorlint
    - gosec
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
        - name: exported
        - name: var-naming
        - name: indent-error-flow
        - name: error-strings
        - name: error-return
        - name: if-return
        - name: superfluous-else
        - name: unreachable-code
        - name: unused-parameter
        - name: context-as-argument
        - name: dot-imports
        - name: blank-imports
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: confusing-naming
        - name: get-return
        - name: deep-exit
        - name: add-constant
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: function-length
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: argument-limit
          disabled: true
        - name: file-header
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
      - path: proto/
        linters:
          - all
      - path: docs/api/
        linters:
          - all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
