// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: taas/billing/v1/billing.proto

package billingv1

import (
	v1 "github.com/go-taas/go-taas/proto/taas/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPriceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelId         string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	AcceleratorType string                 `protobuf:"bytes,2,opt,name=accelerator_type,json=acceleratorType,proto3" json:"accelerator_type,omitempty"`
	// input_price_per_million is the price of one million input tokens, in
	// the platform's billing currency unit.
	InputPricePerMillion  float64 `protobuf:"fixed64,3,opt,name=input_price_per_million,json=inputPricePerMillion,proto3" json:"input_price_per_million,omitempty"`
	OutputPricePerMillion float64 `protobuf:"fixed64,4,opt,name=output_price_per_million,json=outputPricePerMillion,proto3" json:"output_price_per_million,omitempty"`
	Currency              string  `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetPriceRequest) Reset() {
	*x = SetPriceRequest{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPriceRequest) ProtoMessage() {}

func (x *SetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPriceRequest.ProtoReflect.Descriptor instead.
func (*SetPriceRequest) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *SetPriceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetPriceRequest) GetAcceleratorType() string {
	if x != nil {
		return x.AcceleratorType
	}
	return ""
}

func (x *SetPriceRequest) GetInputPricePerMillion() float64 {
	if x != nil {
		return x.InputPricePerMillion
	}
	return 0
}

func (x *SetPriceRequest) GetOutputPricePerMillion() float64 {
	if x != nil {
		return x.OutputPricePerMillion
	}
	return 0
}

func (x *SetPriceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type SetPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPriceResponse) Reset() {
	*x = SetPriceResponse{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPriceResponse) ProtoMessage() {}

func (x *SetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPriceResponse.ProtoReflect.Descriptor instead.
func (*SetPriceResponse) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *SetPriceResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricesRequest) Reset() {
	*x = ListPricesRequest{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricesRequest) ProtoMessage() {}

func (x *ListPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricesRequest.ProtoReflect.Descriptor instead.
func (*ListPricesRequest) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ListPricesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPricesRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ListPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Prices        []*PriceEntry          `protobuf:"bytes,2,rep,name=prices,proto3" json:"prices,omitempty"`
	PageMeta      *v1.PageMeta           `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPricesResponse) Reset() {
	*x = ListPricesResponse{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPricesResponse) ProtoMessage() {}

func (x *ListPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPricesResponse.ProtoReflect.Descriptor instead.
func (*ListPricesResponse) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ListPricesResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListPricesResponse) GetPrices() []*PriceEntry {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *ListPricesResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type PriceEntry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ModelId               string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	AcceleratorType       string                 `protobuf:"bytes,2,opt,name=accelerator_type,json=acceleratorType,proto3" json:"accelerator_type,omitempty"`
	InputPricePerMillion  float64                `protobuf:"fixed64,3,opt,name=input_price_per_million,json=inputPricePerMillion,proto3" json:"input_price_per_million,omitempty"`
	OutputPricePerMillion float64                `protobuf:"fixed64,4,opt,name=output_price_per_million,json=outputPricePerMillion,proto3" json:"output_price_per_million,omitempty"`
	Currency              string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdatedAt             int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PriceEntry) Reset() {
	*x = PriceEntry{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceEntry) ProtoMessage() {}

func (x *PriceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceEntry.ProtoReflect.Descriptor instead.
func (*PriceEntry) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *PriceEntry) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PriceEntry) GetAcceleratorType() string {
	if x != nil {
		return x.AcceleratorType
	}
	return ""
}

func (x *PriceEntry) GetInputPricePerMillion() float64 {
	if x != nil {
		return x.InputPricePerMillion
	}
	return 0
}

func (x *PriceEntry) GetOutputPricePerMillion() float64 {
	if x != nil {
		return x.OutputPricePerMillion
	}
	return 0
}

func (x *PriceEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PriceEntry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetBalanceResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Response *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// mode is "prepaid" (balance) or "postpaid" (quota).
	Mode          string  `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Balance       float64 `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string  `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *GetBalanceResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetBalanceResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ListBillsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Since          int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	Until          int64                  `protobuf:"varint,4,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBillsRequest) Reset() {
	*x = ListBillsRequest{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillsRequest) ProtoMessage() {}

func (x *ListBillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillsRequest.ProtoReflect.Descriptor instead.
func (*ListBillsRequest) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{7}
}

func (x *ListBillsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListBillsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListBillsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *ListBillsRequest) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

type ListBillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Bills         []*BillSummary         `protobuf:"bytes,2,rep,name=bills,proto3" json:"bills,omitempty"`
	PageMeta      *v1.PageMeta           `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBillsResponse) Reset() {
	*x = ListBillsResponse{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBillsResponse) ProtoMessage() {}

func (x *ListBillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBillsResponse.ProtoReflect.Descriptor instead.
func (*ListBillsResponse) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{8}
}

func (x *ListBillsResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListBillsResponse) GetBills() []*BillSummary {
	if x != nil {
		return x.Bills
	}
	return nil
}

func (x *ListBillsResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type BillSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BillId         string                 `protobuf:"bytes,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PeriodStart    int64                  `protobuf:"varint,5,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd      int64                  `protobuf:"varint,6,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BillSummary) Reset() {
	*x = BillSummary{}
	mi := &file_taas_billing_v1_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillSummary) ProtoMessage() {}

func (x *BillSummary) ProtoReflect() protoreflect.Message {
	mi := &file_taas_billing_v1_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillSummary.ProtoReflect.Descriptor instead.
func (*BillSummary) Descriptor() ([]byte, []int) {
	return file_taas_billing_v1_billing_proto_rawDescGZIP(), []int{9}
}

func (x *BillSummary) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *BillSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *BillSummary) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BillSummary) GetPeriodStart() int64 {
	if x != nil {
		return x.PeriodStart
	}
	return 0
}

func (x *BillSummary) GetPeriodEnd() int64 {
	if x != nil {
		return x.PeriodEnd
	}
	return 0
}

var File_taas_billing_v1_billing_proto protoreflect.FileDescriptor

const file_taas_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1dtaas/billing/v1/billing.proto\x12\x0ftaas.billing.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1btaas/common/v1/common.proto\"\xe3\x01\n" +
	"\x0fSetPriceRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12)\n" +
	"\x10accelerator_type\x18\x02 \x01(\tR\x0facceleratorType\x125\n" +
	"\x17input_price_per_million\x18\x03 \x01(\x01R\x14inputPricePerMillion\x127\n" +
	"\x18output_price_per_million\x18\x04 \x01(\x01R\x15outputPricePerMillion\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"H\n" +
	"\x10SetPriceResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\"_\n" +
	"\x11ListPricesRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"\xb6\x01\n" +
	"\x12ListPricesResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x123\n" +
	"\x06prices\x18\x02 \x03(\v2\x1b.taas.billing.v1.PriceEntryR\x06prices\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xfd\x01\n" +
	"\n" +
	"PriceEntry\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12)\n" +
	"\x10accelerator_type\x18\x02 \x01(\tR\x0facceleratorType\x125\n" +
	"\x17input_price_per_million\x18\x03 \x01(\x01R\x14inputPricePerMillion\x127\n" +
	"\x18output_price_per_million\x18\x04 \x01(\x01R\x15outputPricePerMillion\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"<\n" +
	"\x11GetBalanceRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\x94\x01\n" +
	"\x12GetBalanceResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\x98\x01\n" +
	"\x10ListBillsRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x14\n" +
	"\x05until\x18\x04 \x01(\x03R\x05until\"\xb4\x01\n" +
	"\x11ListBillsResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x122\n" +
	"\x05bills\x18\x02 \x03(\v2\x1c.taas.billing.v1.BillSummaryR\x05bills\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xc5\x01\n" +
	"\vBillSummary\x12\x17\n" +
	"\abill_id\x18\x01 \x01(\tR\x06billId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12!\n" +
	"\fperiod_start\x18\x05 \x01(\x03R\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x06 \x01(\x03R\tperiodEnd2\xe6\x03\n" +
	"\x0eBillingService\x12r\n" +
	"\bSetPrice\x12 .taas.billing.v1.SetPriceRequest\x1a!.taas.billing.v1.SetPriceResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/v1/billing/prices\x12u\n" +
	"\n" +
	"ListPrices\x12\".taas.billing.v1.ListPricesRequest\x1a#.taas.billing.v1.ListPricesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/billing/prices\x12v\n" +
	"\n" +
	"GetBalance\x12\".taas.billing.v1.GetBalanceRequest\x1a#.taas.billing.v1.GetBalanceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/billing/balance\x12q\n" +
	"\tListBills\x12!.taas.billing.v1.ListBillsRequest\x1a\".taas.billing.v1.ListBillsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/billing/billsB\xbd\x01\n" +
	"\x13com.taas.billing.v1B\fBillingProtoP\x01Z:github.com/go-taas/go-taas/proto/taas/billing/v1;billingv1\xa2\x02\x03TBX\xaa\x02\x0fTaas.Billing.V1\xca\x02\x0fTaas\\Billing\\V1\xe2\x02\x1bTaas\\Billing\\V1\\GPBMetadata\xea\x02\x11Taas::Billing::V1b\x06proto3"

var (
	file_taas_billing_v1_billing_proto_rawDescOnce sync.Once
	file_taas_billing_v1_billing_proto_rawDescData []byte
)

func file_taas_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_taas_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_taas_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taas_billing_v1_billing_proto_rawDesc), len(file_taas_billing_v1_billing_proto_rawDesc)))
	})
	return file_taas_billing_v1_billing_proto_rawDescData
}

var file_taas_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_taas_billing_v1_billing_proto_goTypes = []any{
	(*SetPriceRequest)(nil),    // 0: taas.billing.v1.SetPriceRequest
	(*SetPriceResponse)(nil),   // 1: taas.billing.v1.SetPriceResponse
	(*ListPricesRequest)(nil),  // 2: taas.billing.v1.ListPricesRequest
	(*ListPricesResponse)(nil), // 3: taas.billing.v1.ListPricesResponse
	(*PriceEntry)(nil),         // 4: taas.billing.v1.PriceEntry
	(*GetBalanceRequest)(nil),  // 5: taas.billing.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil), // 6: taas.billing.v1.GetBalanceResponse
	(*ListBillsRequest)(nil),   // 7: taas.billing.v1.ListBillsRequest
	(*ListBillsResponse)(nil),  // 8: taas.billing.v1.ListBillsResponse
	(*BillSummary)(nil),        // 9: taas.billing.v1.BillSummary
	(*v1.Response)(nil),        // 10: taas.common.v1.Response
	(*v1.PageRequest)(nil),     // 11: taas.common.v1.PageRequest
	(*v1.PageMeta)(nil),        // 12: taas.common.v1.PageMeta
}
var file_taas_billing_v1_billing_proto_depIdxs = []int32{
	10, // 0: taas.billing.v1.SetPriceResponse.response:type_name -> taas.common.v1.Response
	11, // 1: taas.billing.v1.ListPricesRequest.page:type_name -> taas.common.v1.PageRequest
	10, // 2: taas.billing.v1.ListPricesResponse.response:type_name -> taas.common.v1.Response
	4,  // 3: taas.billing.v1.ListPricesResponse.prices:type_name -> taas.billing.v1.PriceEntry
	12, // 4: taas.billing.v1.ListPricesResponse.page_meta:type_name -> taas.common.v1.PageMeta
	10, // 5: taas.billing.v1.GetBalanceResponse.response:type_name -> taas.common.v1.Response
	11, // 6: taas.billing.v1.ListBillsRequest.page:type_name -> taas.common.v1.PageRequest
	10, // 7: taas.billing.v1.ListBillsResponse.response:type_name -> taas.common.v1.Response
	9,  // 8: taas.billing.v1.ListBillsResponse.bills:type_name -> taas.billing.v1.BillSummary
	12, // 9: taas.billing.v1.ListBillsResponse.page_meta:type_name -> taas.common.v1.PageMeta
	0,  // 10: taas.billing.v1.BillingService.SetPrice:input_type -> taas.billing.v1.SetPriceRequest
	2,  // 11: taas.billing.v1.BillingService.ListPrices:input_type -> taas.billing.v1.ListPricesRequest
	5,  // 12: taas.billing.v1.BillingService.GetBalance:input_type -> taas.billing.v1.GetBalanceRequest
	7,  // 13: taas.billing.v1.BillingService.ListBills:input_type -> taas.billing.v1.ListBillsRequest
	1,  // 14: taas.billing.v1.BillingService.SetPrice:output_type -> taas.billing.v1.SetPriceResponse
	3,  // 15: taas.billing.v1.BillingService.ListPrices:output_type -> taas.billing.v1.ListPricesResponse
	6,  // 16: taas.billing.v1.BillingService.GetBalance:output_type -> taas.billing.v1.GetBalanceResponse
	8,  // 17: taas.billing.v1.BillingService.ListBills:output_type -> taas.billing.v1.ListBillsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_taas_billing_v1_billing_proto_init() }
func file_taas_billing_v1_billing_proto_init() {
	if File_taas_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taas_billing_v1_billing_proto_rawDesc), len(file_taas_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taas_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_taas_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_taas_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_taas_billing_v1_billing_proto = out.File
	file_taas_billing_v1_billing_proto_goTypes = nil
	file_taas_billing_v1_billing_proto_depIdxs = nil
}
