// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: taas/infer/v1/infer.proto

package inferv1

import (
	v1 "github.com/go-taas/go-taas/proto/taas/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInferenceServiceRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelId      string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ImageId      string                 `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Replicas     int32                  `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// accelerator names the hardware platform (nvidia, iluvatar, metax).
	Accelerator string `protobuf:"bytes,6,opt,name=accelerator,proto3" json:"accelerator,omitempty"`
	// accelerator_type is the concrete card model requested.
	AcceleratorType string `protobuf:"bytes,7,opt,name=accelerator_type,json=acceleratorType,proto3" json:"accelerator_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateInferenceServiceRequest) Reset() {
	*x = CreateInferenceServiceRequest{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInferenceServiceRequest) ProtoMessage() {}

func (x *CreateInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInferenceServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *CreateInferenceServiceRequest) GetAccelerator() string {
	if x != nil {
		return x.Accelerator
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetAcceleratorType() string {
	if x != nil {
		return x.AcceleratorType
	}
	return ""
}

type CreateInferenceServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInferenceServiceResponse) Reset() {
	*x = CreateInferenceServiceResponse{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInferenceServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInferenceServiceResponse) ProtoMessage() {}

func (x *CreateInferenceServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInferenceServiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInferenceServiceResponse) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInferenceServiceResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateInferenceServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ListInferenceServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInferenceServicesRequest) Reset() {
	*x = ListInferenceServicesRequest{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInferenceServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInferenceServicesRequest) ProtoMessage() {}

func (x *ListInferenceServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInferenceServicesRequest.ProtoReflect.Descriptor instead.
func (*ListInferenceServicesRequest) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{2}
}

func (x *ListInferenceServicesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListInferenceServicesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Response      *v1.Response               `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Services      []*InferenceServiceSummary `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	PageMeta      *v1.PageMeta               `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInferenceServicesResponse) Reset() {
	*x = ListInferenceServicesResponse{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInferenceServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInferenceServicesResponse) ProtoMessage() {}

func (x *ListInferenceServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInferenceServicesResponse.ProtoReflect.Descriptor instead.
func (*ListInferenceServicesResponse) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{3}
}

func (x *ListInferenceServicesResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListInferenceServicesResponse) GetServices() []*InferenceServiceSummary {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListInferenceServicesResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type InferenceServiceSummary struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ServiceId    string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelId      string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ImageId      string                 `protobuf:"bytes,5,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Replicas     int32                  `protobuf:"varint,6,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// state is the observed lifecycle state: pending, deploying, running,
	// failed, terminated.
	State         string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	UpdatedAt     int64  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceServiceSummary) Reset() {
	*x = InferenceServiceSummary{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceServiceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceServiceSummary) ProtoMessage() {}

func (x *InferenceServiceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceServiceSummary.ProtoReflect.Descriptor instead.
func (*InferenceServiceSummary) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{4}
}

func (x *InferenceServiceSummary) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *InferenceServiceSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferenceServiceSummary) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *InferenceServiceSummary) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *InferenceServiceSummary) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *InferenceServiceSummary) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *InferenceServiceSummary) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InferenceServiceSummary) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetInferenceServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceServiceRequest) Reset() {
	*x = GetInferenceServiceRequest{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceServiceRequest) ProtoMessage() {}

func (x *GetInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*GetInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{5}
}

func (x *GetInferenceServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type GetInferenceServiceResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Response      *v1.Response             `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Service       *InferenceServiceSummary `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Endpoints     []string                 `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceServiceResponse) Reset() {
	*x = GetInferenceServiceResponse{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceServiceResponse) ProtoMessage() {}

func (x *GetInferenceServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceServiceResponse.ProtoReflect.Descriptor instead.
func (*GetInferenceServiceResponse) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{6}
}

func (x *GetInferenceServiceResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetInferenceServiceResponse) GetService() *InferenceServiceSummary {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *GetInferenceServiceResponse) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type ScaleInferenceServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleInferenceServiceRequest) Reset() {
	*x = ScaleInferenceServiceRequest{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleInferenceServiceRequest) ProtoMessage() {}

func (x *ScaleInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*ScaleInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{7}
}

func (x *ScaleInferenceServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ScaleInferenceServiceRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type ScaleInferenceServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleInferenceServiceResponse) Reset() {
	*x = ScaleInferenceServiceResponse{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleInferenceServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleInferenceServiceResponse) ProtoMessage() {}

func (x *ScaleInferenceServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleInferenceServiceResponse.ProtoReflect.Descriptor instead.
func (*ScaleInferenceServiceResponse) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{8}
}

func (x *ScaleInferenceServiceResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type DeleteInferenceServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInferenceServiceRequest) Reset() {
	*x = DeleteInferenceServiceRequest{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInferenceServiceRequest) ProtoMessage() {}

func (x *DeleteInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteInferenceServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeleteInferenceServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInferenceServiceResponse) Reset() {
	*x = DeleteInferenceServiceResponse{}
	mi := &file_taas_infer_v1_infer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInferenceServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInferenceServiceResponse) ProtoMessage() {}

func (x *DeleteInferenceServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_infer_v1_infer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInferenceServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInferenceServiceResponse) Descriptor() ([]byte, []int) {
	return file_taas_infer_v1_infer_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteInferenceServiceResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_taas_infer_v1_infer_proto protoreflect.FileDescriptor

const file_taas_infer_v1_infer_proto_rawDesc = "" +
	"\n" +
	"\x19taas/infer/v1/infer.proto\x12\rtaas.infer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1btaas/common/v1/common.proto\"\xf7\x01\n" +
	"\x1dCreateInferenceServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\tR\aimageId\x12\x1a\n" +
	"\breplicas\x18\x05 \x01(\x05R\breplicas\x12 \n" +
	"\vaccelerator\x18\x06 \x01(\tR\vaccelerator\x12)\n" +
	"\x10accelerator_type\x18\a \x01(\tR\x0facceleratorType\"u\n" +
	"\x1eCreateInferenceServiceResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\"O\n" +
	"\x1cListInferenceServicesRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\"\xd0\x01\n" +
	"\x1dListInferenceServicesResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12B\n" +
	"\bservices\x18\x02 \x03(\v2&.taas.infer.v1.InferenceServiceSummaryR\bservices\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xf8\x01\n" +
	"\x17InferenceServiceSummary\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\x12\x19\n" +
	"\bimage_id\x18\x05 \x01(\tR\aimageId\x12\x1a\n" +
	"\breplicas\x18\x06 \x01(\x05R\breplicas\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\";\n" +
	"\x1aGetInferenceServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"\xb3\x01\n" +
	"\x1bGetInferenceServiceResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12@\n" +
	"\aservice\x18\x02 \x01(\v2&.taas.infer.v1.InferenceServiceSummaryR\aservice\x12\x1c\n" +
	"\tendpoints\x18\x03 \x03(\tR\tendpoints\"Y\n" +
	"\x1cScaleInferenceServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\"U\n" +
	"\x1dScaleInferenceServiceResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\">\n" +
	"\x1dDeleteInferenceServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"V\n" +
	"\x1eDeleteInferenceServiceResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse2\xc5\x06\n" +
	"\x13InferServiceService\x12\x9c\x01\n" +
	"\x16CreateInferenceService\x12,.taas.infer.v1.CreateInferenceServiceRequest\x1a-.taas.infer.v1.CreateInferenceServiceResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/inference-services\x12\x96\x01\n" +
	"\x15ListInferenceServices\x12+.taas.infer.v1.ListInferenceServicesRequest\x1a,.taas.infer.v1.ListInferenceServicesResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/inference-services\x12\x9d\x01\n" +
	"\x13GetInferenceService\x12).taas.infer.v1.GetInferenceServiceRequest\x1a*.taas.infer.v1.GetInferenceServiceResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/inference-services/{service_id}\x12\xac\x01\n" +
	"\x15ScaleInferenceService\x12+.taas.infer.v1.ScaleInferenceServiceRequest\x1a,.taas.infer.v1.ScaleInferenceServiceResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/api/v1/inference-services/{service_id}:scale\x12\xa6\x01\n" +
	"\x16DeleteInferenceService\x12,.taas.infer.v1.DeleteInferenceServiceRequest\x1a-.taas.infer.v1.DeleteInferenceServiceResponse\"/\x82\xd3\xe4\x93\x02)*'/api/v1/inference-services/{service_id}B\xad\x01\n" +
	"\x11com.taas.infer.v1B\n" +
	"InferProtoP\x01Z6github.com/go-taas/go-taas/proto/taas/infer/v1;inferv1\xa2\x02\x03TIX\xaa\x02\rTaas.Infer.V1\xca\x02\rTaas\\Infer\\V1\xe2\x02\x19Taas\\Infer\\V1\\GPBMetadata\xea\x02\x0fTaas::Infer::V1b\x06proto3"

var (
	file_taas_infer_v1_infer_proto_rawDescOnce sync.Once
	file_taas_infer_v1_infer_proto_rawDescData []byte
)

func file_taas_infer_v1_infer_proto_rawDescGZIP() []byte {
	file_taas_infer_v1_infer_proto_rawDescOnce.Do(func() {
		file_taas_infer_v1_infer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taas_infer_v1_infer_proto_rawDesc), len(file_taas_infer_v1_infer_proto_rawDesc)))
	})
	return file_taas_infer_v1_infer_proto_rawDescData
}

var file_taas_infer_v1_infer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_taas_infer_v1_infer_proto_goTypes = []any{
	(*CreateInferenceServiceRequest)(nil),  // 0: taas.infer.v1.CreateInferenceServiceRequest
	(*CreateInferenceServiceResponse)(nil), // 1: taas.infer.v1.CreateInferenceServiceResponse
	(*ListInferenceServicesRequest)(nil),   // 2: taas.infer.v1.ListInferenceServicesRequest
	(*ListInferenceServicesResponse)(nil),  // 3: taas.infer.v1.ListInferenceServicesResponse
	(*InferenceServiceSummary)(nil),        // 4: taas.infer.v1.InferenceServiceSummary
	(*GetInferenceServiceRequest)(nil),     // 5: taas.infer.v1.GetInferenceServiceRequest
	(*GetInferenceServiceResponse)(nil),    // 6: taas.infer.v1.GetInferenceServiceResponse
	(*ScaleInferenceServiceRequest)(nil),   // 7: taas.infer.v1.ScaleInferenceServiceRequest
	(*ScaleInferenceServiceResponse)(nil),  // 8: taas.infer.v1.ScaleInferenceServiceResponse
	(*DeleteInferenceServiceRequest)(nil),  // 9: taas.infer.v1.DeleteInferenceServiceRequest
	(*DeleteInferenceServiceResponse)(nil), // 10: taas.infer.v1.DeleteInferenceServiceResponse
	(*v1.Response)(nil),                    // 11: taas.common.v1.Response
	(*v1.PageRequest)(nil),                 // 12: taas.common.v1.PageRequest
	(*v1.PageMeta)(nil),                    // 13: taas.common.v1.PageMeta
}
var file_taas_infer_v1_infer_proto_depIdxs = []int32{
	11, // 0: taas.infer.v1.CreateInferenceServiceResponse.response:type_name -> taas.common.v1.Response
	12, // 1: taas.infer.v1.ListInferenceServicesRequest.page:type_name -> taas.common.v1.PageRequest
	11, // 2: taas.infer.v1.ListInferenceServicesResponse.response:type_name -> taas.common.v1.Response
	4,  // 3: taas.infer.v1.ListInferenceServicesResponse.services:type_name -> taas.infer.v1.InferenceServiceSummary
	13, // 4: taas.infer.v1.ListInferenceServicesResponse.page_meta:type_name -> taas.common.v1.PageMeta
	11, // 5: taas.infer.v1.GetInferenceServiceResponse.response:type_name -> taas.common.v1.Response
	4,  // 6: taas.infer.v1.GetInferenceServiceResponse.service:type_name -> taas.infer.v1.InferenceServiceSummary
	11, // 7: taas.infer.v1.ScaleInferenceServiceResponse.response:type_name -> taas.common.v1.Response
	11, // 8: taas.infer.v1.DeleteInferenceServiceResponse.response:type_name -> taas.common.v1.Response
	0,  // 9: taas.infer.v1.InferServiceService.CreateInferenceService:input_type -> taas.infer.v1.CreateInferenceServiceRequest
	2,  // 10: taas.infer.v1.InferServiceService.ListInferenceServices:input_type -> taas.infer.v1.ListInferenceServicesRequest
	5,  // 11: taas.infer.v1.InferServiceService.GetInferenceService:input_type -> taas.infer.v1.GetInferenceServiceRequest
	7,  // 12: taas.infer.v1.InferServiceService.ScaleInferenceService:input_type -> taas.infer.v1.ScaleInferenceServiceRequest
	9,  // 13: taas.infer.v1.InferServiceService.DeleteInferenceService:input_type -> taas.infer.v1.DeleteInferenceServiceRequest
	1,  // 14: taas.infer.v1.InferServiceService.CreateInferenceService:output_type -> taas.infer.v1.CreateInferenceServiceResponse
	3,  // 15: taas.infer.v1.InferServiceService.ListInferenceServices:output_type -> taas.infer.v1.ListInferenceServicesResponse
	6,  // 16: taas.infer.v1.InferServiceService.GetInferenceService:output_type -> taas.infer.v1.GetInferenceServiceResponse
	8,  // 17: taas.infer.v1.InferServiceService.ScaleInferenceService:output_type -> taas.infer.v1.ScaleInferenceServiceResponse
	10, // 18: taas.infer.v1.InferServiceService.DeleteInferenceService:output_type -> taas.infer.v1.DeleteInferenceServiceResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_taas_infer_v1_infer_proto_init() }
func file_taas_infer_v1_infer_proto_init() {
	if File_taas_infer_v1_infer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taas_infer_v1_infer_proto_rawDesc), len(file_taas_infer_v1_infer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taas_infer_v1_infer_proto_goTypes,
		DependencyIndexes: file_taas_infer_v1_infer_proto_depIdxs,
		MessageInfos:      file_taas_infer_v1_infer_proto_msgTypes,
	}.Build()
	File_taas_infer_v1_infer_proto = out.File
	file_taas_infer_v1_infer_proto_goTypes = nil
	file_taas_infer_v1_infer_proto_depIdxs = nil
}
