// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: taas/infer/v1/infer.proto

package inferv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferServiceService_CreateInferenceService_FullMethodName = "/taas.infer.v1.InferServiceService/CreateInferenceService"
	InferServiceService_ListInferenceServices_FullMethodName  = "/taas.infer.v1.InferServiceService/ListInferenceServices"
	InferServiceService_GetInferenceService_FullMethodName    = "/taas.infer.v1.InferServiceService/GetInferenceService"
	InferServiceService_ScaleInferenceService_FullMethodName  = "/taas.infer.v1.InferServiceService/ScaleInferenceService"
	InferServiceService_DeleteInferenceService_FullMethodName = "/taas.infer.v1.InferServiceService/DeleteInferenceService"
)

// InferServiceServiceClient is the client API for InferServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferServiceService manages the lifecycle of inference services:
// desired-state maintenance, change publication to the message queue and
// endpoint registration for the data-plane gateway.
type InferServiceServiceClient interface {
	// CreateInferenceService deploys a model with the given image and
	// replicas. The change is published to the message queue and applied
	// by the controller.
	CreateInferenceService(ctx context.Context, in *CreateInferenceServiceRequest, opts ...grpc.CallOption) (*CreateInferenceServiceResponse, error)
	// ListInferenceServices returns inference services of the caller's
	// organization.
	ListInferenceServices(ctx context.Context, in *ListInferenceServicesRequest, opts ...grpc.CallOption) (*ListInferenceServicesResponse, error)
	// GetInferenceService returns one inference service with its endpoints.
	GetInferenceService(ctx context.Context, in *GetInferenceServiceRequest, opts ...grpc.CallOption) (*GetInferenceServiceResponse, error)
	// ScaleInferenceService changes the replica count.
	ScaleInferenceService(ctx context.Context, in *ScaleInferenceServiceRequest, opts ...grpc.CallOption) (*ScaleInferenceServiceResponse, error)
	// DeleteInferenceService tears an inference service down.
	DeleteInferenceService(ctx context.Context, in *DeleteInferenceServiceRequest, opts ...grpc.CallOption) (*DeleteInferenceServiceResponse, error)
}

type inferServiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferServiceServiceClient(cc grpc.ClientConnInterface) InferServiceServiceClient {
	return &inferServiceServiceClient{cc}
}

func (c *inferServiceServiceClient) CreateInferenceService(ctx context.Context, in *CreateInferenceServiceRequest, opts ...grpc.CallOption) (*CreateInferenceServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInferenceServiceResponse)
	err := c.cc.Invoke(ctx, InferServiceService_CreateInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferServiceServiceClient) ListInferenceServices(ctx context.Context, in *ListInferenceServicesRequest, opts ...grpc.CallOption) (*ListInferenceServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInferenceServicesResponse)
	err := c.cc.Invoke(ctx, InferServiceService_ListInferenceServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferServiceServiceClient) GetInferenceService(ctx context.Context, in *GetInferenceServiceRequest, opts ...grpc.CallOption) (*GetInferenceServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInferenceServiceResponse)
	err := c.cc.Invoke(ctx, InferServiceService_GetInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferServiceServiceClient) ScaleInferenceService(ctx context.Context, in *ScaleInferenceServiceRequest, opts ...grpc.CallOption) (*ScaleInferenceServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleInferenceServiceResponse)
	err := c.cc.Invoke(ctx, InferServiceService_ScaleInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferServiceServiceClient) DeleteInferenceService(ctx context.Context, in *DeleteInferenceServiceRequest, opts ...grpc.CallOption) (*DeleteInferenceServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInferenceServiceResponse)
	err := c.cc.Invoke(ctx, InferServiceService_DeleteInferenceService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferServiceServiceServer is the server API for InferServiceService service.
// All implementations must embed UnimplementedInferServiceServiceServer
// for forward compatibility.
//
// InferServiceService manages the lifecycle of inference services:
// desired-state maintenance, change publication to the message queue and
// endpoint registration for the data-plane gateway.
type InferServiceServiceServer interface {
	// CreateInferenceService deploys a model with the given image and
	// replicas. The change is published to the message queue and applied
	// by the controller.
	CreateInferenceService(context.Context, *CreateInferenceServiceRequest) (*CreateInferenceServiceResponse, error)
	// ListInferenceServices returns inference services of the caller's
	// organization.
	ListInferenceServices(context.Context, *ListInferenceServicesRequest) (*ListInferenceServicesResponse, error)
	// GetInferenceService returns one inference service with its endpoints.
	GetInferenceService(context.Context, *GetInferenceServiceRequest) (*GetInferenceServiceResponse, error)
	// ScaleInferenceService changes the replica count.
	ScaleInferenceService(context.Context, *ScaleInferenceServiceRequest) (*ScaleInferenceServiceResponse, error)
	// DeleteInferenceService tears an inference service down.
	DeleteInferenceService(context.Context, *DeleteInferenceServiceRequest) (*DeleteInferenceServiceResponse, error)
	mustEmbedUnimplementedInferServiceServiceServer()
}

// UnimplementedInferServiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferServiceServiceServer struct{}

func (UnimplementedInferServiceServiceServer) CreateInferenceService(context.Context, *CreateInferenceServiceRequest) (*CreateInferenceServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInferenceService not implemented")
}
func (UnimplementedInferServiceServiceServer) ListInferenceServices(context.Context, *ListInferenceServicesRequest) (*ListInferenceServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInferenceServices not implemented")
}
func (UnimplementedInferServiceServiceServer) GetInferenceService(context.Context, *GetInferenceServiceRequest) (*GetInferenceServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInferenceService not implemented")
}
func (UnimplementedInferServiceServiceServer) ScaleInferenceService(context.Context, *ScaleInferenceServiceRequest) (*ScaleInferenceServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScaleInferenceService not implemented")
}
func (UnimplementedInferServiceServiceServer) DeleteInferenceService(context.Context, *DeleteInferenceServiceRequest) (*DeleteInferenceServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInferenceService not implemented")
}
func (UnimplementedInferServiceServiceServer) mustEmbedUnimplementedInferServiceServiceServer() {}
func (UnimplementedInferServiceServiceServer) testEmbeddedByValue()                             {}

// UnsafeInferServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferServiceServiceServer will
// result in compilation errors.
type UnsafeInferServiceServiceServer interface {
	mustEmbedUnimplementedInferServiceServiceServer()
}

func RegisterInferServiceServiceServer(s grpc.ServiceRegistrar, srv InferServiceServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferServiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferServiceService_ServiceDesc, srv)
}

func _InferServiceService_CreateInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferServiceServiceServer).CreateInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferServiceService_CreateInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferServiceServiceServer).CreateInferenceService(ctx, req.(*CreateInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferServiceService_ListInferenceServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInferenceServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferServiceServiceServer).ListInferenceServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferServiceService_ListInferenceServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferServiceServiceServer).ListInferenceServices(ctx, req.(*ListInferenceServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferServiceService_GetInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferServiceServiceServer).GetInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferServiceService_GetInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferServiceServiceServer).GetInferenceService(ctx, req.(*GetInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferServiceService_ScaleInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferServiceServiceServer).ScaleInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferServiceService_ScaleInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferServiceServiceServer).ScaleInferenceService(ctx, req.(*ScaleInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferServiceService_DeleteInferenceService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferServiceServiceServer).DeleteInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferServiceService_DeleteInferenceService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferServiceServiceServer).DeleteInferenceService(ctx, req.(*DeleteInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferServiceService_ServiceDesc is the grpc.ServiceDesc for InferServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taas.infer.v1.InferServiceService",
	HandlerType: (*InferServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInferenceService",
			Handler:    _InferServiceService_CreateInferenceService_Handler,
		},
		{
			MethodName: "ListInferenceServices",
			Handler:    _InferServiceService_ListInferenceServices_Handler,
		},
		{
			MethodName: "GetInferenceService",
			Handler:    _InferServiceService_GetInferenceService_Handler,
		},
		{
			MethodName: "ScaleInferenceService",
			Handler:    _InferServiceService_ScaleInferenceService_Handler,
		},
		{
			MethodName: "DeleteInferenceService",
			Handler:    _InferServiceService_DeleteInferenceService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taas/infer/v1/infer.proto",
}
