// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: taas/metering/v1/metering.proto

package meteringv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeteringService_IngestMeteringEvent_FullMethodName = "/taas.metering.v1.MeteringService/IngestMeteringEvent"
	MeteringService_ListVouchers_FullMethodName        = "/taas.metering.v1.MeteringService/ListVouchers"
)

// MeteringServiceClient is the client API for MeteringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeteringService consumes token-usage events from the data-plane gateway,
// produces tamper-evident metering vouchers and forwards settlement
// events to the billing pipeline.
type MeteringServiceClient interface {
	// IngestMeteringEvent records one token-usage event. It is called by
	// the gateway's Wasm plugin through the message queue (or directly in
	// tests).
	IngestMeteringEvent(ctx context.Context, in *IngestMeteringEventRequest, opts ...grpc.CallOption) (*IngestMeteringEventResponse, error)
	// ListVouchers returns metering vouchers for auditing.
	ListVouchers(ctx context.Context, in *ListVouchersRequest, opts ...grpc.CallOption) (*ListVouchersResponse, error)
}

type meteringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeteringServiceClient(cc grpc.ClientConnInterface) MeteringServiceClient {
	return &meteringServiceClient{cc}
}

func (c *meteringServiceClient) IngestMeteringEvent(ctx context.Context, in *IngestMeteringEventRequest, opts ...grpc.CallOption) (*IngestMeteringEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestMeteringEventResponse)
	err := c.cc.Invoke(ctx, MeteringService_IngestMeteringEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meteringServiceClient) ListVouchers(ctx context.Context, in *ListVouchersRequest, opts ...grpc.CallOption) (*ListVouchersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVouchersResponse)
	err := c.cc.Invoke(ctx, MeteringService_ListVouchers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeteringServiceServer is the server API for MeteringService service.
// All implementations must embed UnimplementedMeteringServiceServer
// for forward compatibility.
//
// MeteringService consumes token-usage events from the data-plane gateway,
// produces tamper-evident metering vouchers and forwards settlement
// events to the billing pipeline.
type MeteringServiceServer interface {
	// IngestMeteringEvent records one token-usage event. It is called by
	// the gateway's Wasm plugin through the message queue (or directly in
	// tests).
	IngestMeteringEvent(context.Context, *IngestMeteringEventRequest) (*IngestMeteringEventResponse, error)
	// ListVouchers returns metering vouchers for auditing.
	ListVouchers(context.Context, *ListVouchersRequest) (*ListVouchersResponse, error)
	mustEmbedUnimplementedMeteringServiceServer()
}

// UnimplementedMeteringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeteringServiceServer struct{}

func (UnimplementedMeteringServiceServer) IngestMeteringEvent(context.Context, *IngestMeteringEventRequest) (*IngestMeteringEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestMeteringEvent not implemented")
}
func (UnimplementedMeteringServiceServer) ListVouchers(context.Context, *ListVouchersRequest) (*ListVouchersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVouchers not implemented")
}
func (UnimplementedMeteringServiceServer) mustEmbedUnimplementedMeteringServiceServer() {}
func (UnimplementedMeteringServiceServer) testEmbeddedByValue()                         {}

// UnsafeMeteringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeteringServiceServer will
// result in compilation errors.
type UnsafeMeteringServiceServer interface {
	mustEmbedUnimplementedMeteringServiceServer()
}

func RegisterMeteringServiceServer(s grpc.ServiceRegistrar, srv MeteringServiceServer) {
	// If the following call pancis, it indicates UnimplementedMeteringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeteringService_ServiceDesc, srv)
}

func _MeteringService_IngestMeteringEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestMeteringEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeteringServiceServer).IngestMeteringEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeteringService_IngestMeteringEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeteringServiceServer).IngestMeteringEvent(ctx, req.(*IngestMeteringEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeteringService_ListVouchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVouchersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeteringServiceServer).ListVouchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeteringService_ListVouchers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeteringServiceServer).ListVouchers(ctx, req.(*ListVouchersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeteringService_ServiceDesc is the grpc.ServiceDesc for MeteringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeteringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taas.metering.v1.MeteringService",
	HandlerType: (*MeteringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestMeteringEvent",
			Handler:    _MeteringService_IngestMeteringEvent_Handler,
		},
		{
			MethodName: "ListVouchers",
			Handler:    _MeteringService_ListVouchers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taas/metering/v1/metering.proto",
}
