// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: taas/metering/v1/metering.proto

package meteringv1

import (
	v1 "github.com/go-taas/go-taas/proto/taas/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestMeteringEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id uniquely identifies the inference request.
	RequestId      string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ApiKeyId       string `protobuf:"bytes,3,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	ModelId        string `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// token_usage carries the per-part token counts.
	Usage         *TokenUsage `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	CompletedAt   int64       `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMeteringEventRequest) Reset() {
	*x = IngestMeteringEventRequest{}
	mi := &file_taas_metering_v1_metering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMeteringEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMeteringEventRequest) ProtoMessage() {}

func (x *IngestMeteringEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_metering_v1_metering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMeteringEventRequest.ProtoReflect.Descriptor instead.
func (*IngestMeteringEventRequest) Descriptor() ([]byte, []int) {
	return file_taas_metering_v1_metering_proto_rawDescGZIP(), []int{0}
}

func (x *IngestMeteringEventRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *IngestMeteringEventRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *IngestMeteringEventRequest) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *IngestMeteringEventRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *IngestMeteringEventRequest) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *IngestMeteringEventRequest) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int64                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	CachedTokens     int64                  `protobuf:"varint,3,opt,name=cached_tokens,json=cachedTokens,proto3" json:"cached_tokens,omitempty"`
	ReasoningTokens  int64                  `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_taas_metering_v1_metering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_taas_metering_v1_metering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_taas_metering_v1_metering_proto_rawDescGZIP(), []int{1}
}

func (x *TokenUsage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetCachedTokens() int64 {
	if x != nil {
		return x.CachedTokens
	}
	return 0
}

func (x *TokenUsage) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

type IngestMeteringEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	VoucherId     string                 `protobuf:"bytes,2,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMeteringEventResponse) Reset() {
	*x = IngestMeteringEventResponse{}
	mi := &file_taas_metering_v1_metering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMeteringEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMeteringEventResponse) ProtoMessage() {}

func (x *IngestMeteringEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_metering_v1_metering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMeteringEventResponse.ProtoReflect.Descriptor instead.
func (*IngestMeteringEventResponse) Descriptor() ([]byte, []int) {
	return file_taas_metering_v1_metering_proto_rawDescGZIP(), []int{2}
}

func (x *IngestMeteringEventResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *IngestMeteringEventResponse) GetVoucherId() string {
	if x != nil {
		return x.VoucherId
	}
	return ""
}

type ListVouchersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Page           *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Since          int64                  `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	Until          int64                  `protobuf:"varint,4,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListVouchersRequest) Reset() {
	*x = ListVouchersRequest{}
	mi := &file_taas_metering_v1_metering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVouchersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVouchersRequest) ProtoMessage() {}

func (x *ListVouchersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_metering_v1_metering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVouchersRequest.ProtoReflect.Descriptor instead.
func (*ListVouchersRequest) Descriptor() ([]byte, []int) {
	return file_taas_metering_v1_metering_proto_rawDescGZIP(), []int{3}
}

func (x *ListVouchersRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListVouchersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListVouchersRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *ListVouchersRequest) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

type ListVouchersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Vouchers      []*VoucherSummary      `protobuf:"bytes,2,rep,name=vouchers,proto3" json:"vouchers,omitempty"`
	PageMeta      *v1.PageMeta           `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVouchersResponse) Reset() {
	*x = ListVouchersResponse{}
	mi := &file_taas_metering_v1_metering_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVouchersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVouchersResponse) ProtoMessage() {}

func (x *ListVouchersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_metering_v1_metering_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVouchersResponse.ProtoReflect.Descriptor instead.
func (*ListVouchersResponse) Descriptor() ([]byte, []int) {
	return file_taas_metering_v1_metering_proto_rawDescGZIP(), []int{4}
}

func (x *ListVouchersResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListVouchersResponse) GetVouchers() []*VoucherSummary {
	if x != nil {
		return x.Vouchers
	}
	return nil
}

func (x *ListVouchersResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type VoucherSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VoucherId      string                 `protobuf:"bytes,1,opt,name=voucher_id,json=voucherId,proto3" json:"voucher_id,omitempty"`
	RequestId      string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ModelId        string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Usage          *TokenUsage            `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	CompletedAt    int64                  `protobuf:"varint,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoucherSummary) Reset() {
	*x = VoucherSummary{}
	mi := &file_taas_metering_v1_metering_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoucherSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherSummary) ProtoMessage() {}

func (x *VoucherSummary) ProtoReflect() protoreflect.Message {
	mi := &file_taas_metering_v1_metering_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherSummary.ProtoReflect.Descriptor instead.
func (*VoucherSummary) Descriptor() ([]byte, []int) {
	return file_taas_metering_v1_metering_proto_rawDescGZIP(), []int{5}
}

func (x *VoucherSummary) GetVoucherId() string {
	if x != nil {
		return x.VoucherId
	}
	return ""
}

func (x *VoucherSummary) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VoucherSummary) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *VoucherSummary) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *VoucherSummary) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *VoucherSummary) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

var File_taas_metering_v1_metering_proto protoreflect.FileDescriptor

const file_taas_metering_v1_metering_proto_rawDesc = "" +
	"\n" +
	"\x1ftaas/metering/v1/metering.proto\x12\x10taas.metering.v1\x1a\x1btaas/common/v1/common.proto\"\xf4\x01\n" +
	"\x1aIngestMeteringEventRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x03 \x01(\tR\bapiKeyId\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x122\n" +
	"\x05usage\x18\x05 \x01(\v2\x1c.taas.metering.v1.TokenUsageR\x05usage\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\x03R\vcompletedAt\"\xae\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x03R\x10completionTokens\x12#\n" +
	"\rcached_tokens\x18\x03 \x01(\x03R\fcachedTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x03R\x0freasoningTokens\"r\n" +
	"\x1bIngestMeteringEventResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x1d\n" +
	"\n" +
	"voucher_id\x18\x02 \x01(\tR\tvoucherId\"\x9b\x01\n" +
	"\x13ListVouchersRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x14\n" +
	"\x05until\x18\x04 \x01(\x03R\x05until\"\xc1\x01\n" +
	"\x14ListVouchersResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12<\n" +
	"\bvouchers\x18\x02 \x03(\v2 .taas.metering.v1.VoucherSummaryR\bvouchers\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xe9\x01\n" +
	"\x0eVoucherSummary\x12\x1d\n" +
	"\n" +
	"voucher_id\x18\x01 \x01(\tR\tvoucherId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x122\n" +
	"\x05usage\x18\x05 \x01(\v2\x1c.taas.metering.v1.TokenUsageR\x05usage\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\x03R\vcompletedAt2\xe4\x01\n" +
	"\x0fMeteringService\x12r\n" +
	"\x13IngestMeteringEvent\x12,.taas.metering.v1.IngestMeteringEventRequest\x1a-.taas.metering.v1.IngestMeteringEventResponse\x12]\n" +
	"\fListVouchers\x12%.taas.metering.v1.ListVouchersRequest\x1a&.taas.metering.v1.ListVouchersResponseB\xc5\x01\n" +
	"\x14com.taas.metering.v1B\rMeteringProtoP\x01Z<github.com/go-taas/go-taas/proto/taas/metering/v1;meteringv1\xa2\x02\x03TMX\xaa\x02\x10Taas.Metering.V1\xca\x02\x10Taas\\Metering\\V1\xe2\x02\x1cTaas\\Metering\\V1\\GPBMetadata\xea\x02\x12Taas::Metering::V1b\x06proto3"

var (
	file_taas_metering_v1_metering_proto_rawDescOnce sync.Once
	file_taas_metering_v1_metering_proto_rawDescData []byte
)

func file_taas_metering_v1_metering_proto_rawDescGZIP() []byte {
	file_taas_metering_v1_metering_proto_rawDescOnce.Do(func() {
		file_taas_metering_v1_metering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taas_metering_v1_metering_proto_rawDesc), len(file_taas_metering_v1_metering_proto_rawDesc)))
	})
	return file_taas_metering_v1_metering_proto_rawDescData
}

var file_taas_metering_v1_metering_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_taas_metering_v1_metering_proto_goTypes = []any{
	(*IngestMeteringEventRequest)(nil),  // 0: taas.metering.v1.IngestMeteringEventRequest
	(*TokenUsage)(nil),                  // 1: taas.metering.v1.TokenUsage
	(*IngestMeteringEventResponse)(nil), // 2: taas.metering.v1.IngestMeteringEventResponse
	(*ListVouchersRequest)(nil),         // 3: taas.metering.v1.ListVouchersRequest
	(*ListVouchersResponse)(nil),        // 4: taas.metering.v1.ListVouchersResponse
	(*VoucherSummary)(nil),              // 5: taas.metering.v1.VoucherSummary
	(*v1.Response)(nil),                 // 6: taas.common.v1.Response
	(*v1.PageRequest)(nil),              // 7: taas.common.v1.PageRequest
	(*v1.PageMeta)(nil),                 // 8: taas.common.v1.PageMeta
}
var file_taas_metering_v1_metering_proto_depIdxs = []int32{
	1, // 0: taas.metering.v1.IngestMeteringEventRequest.usage:type_name -> taas.metering.v1.TokenUsage
	6, // 1: taas.metering.v1.IngestMeteringEventResponse.response:type_name -> taas.common.v1.Response
	7, // 2: taas.metering.v1.ListVouchersRequest.page:type_name -> taas.common.v1.PageRequest
	6, // 3: taas.metering.v1.ListVouchersResponse.response:type_name -> taas.common.v1.Response
	5, // 4: taas.metering.v1.ListVouchersResponse.vouchers:type_name -> taas.metering.v1.VoucherSummary
	8, // 5: taas.metering.v1.ListVouchersResponse.page_meta:type_name -> taas.common.v1.PageMeta
	1, // 6: taas.metering.v1.VoucherSummary.usage:type_name -> taas.metering.v1.TokenUsage
	0, // 7: taas.metering.v1.MeteringService.IngestMeteringEvent:input_type -> taas.metering.v1.IngestMeteringEventRequest
	3, // 8: taas.metering.v1.MeteringService.ListVouchers:input_type -> taas.metering.v1.ListVouchersRequest
	2, // 9: taas.metering.v1.MeteringService.IngestMeteringEvent:output_type -> taas.metering.v1.IngestMeteringEventResponse
	4, // 10: taas.metering.v1.MeteringService.ListVouchers:output_type -> taas.metering.v1.ListVouchersResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_taas_metering_v1_metering_proto_init() }
func file_taas_metering_v1_metering_proto_init() {
	if File_taas_metering_v1_metering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taas_metering_v1_metering_proto_rawDesc), len(file_taas_metering_v1_metering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taas_metering_v1_metering_proto_goTypes,
		DependencyIndexes: file_taas_metering_v1_metering_proto_depIdxs,
		MessageInfos:      file_taas_metering_v1_metering_proto_msgTypes,
	}.Build()
	File_taas_metering_v1_metering_proto = out.File
	file_taas_metering_v1_metering_proto_goTypes = nil
	file_taas_metering_v1_metering_proto_depIdxs = nil
}
