import { useEffect, useRef, useState } from 'react';
import { useApi } from '../../surface';
import { useOrg } from '../../org';
import { useI18n } from '../../i18n';
import { navigate, useParams } from '../../router';
import { Dialog, ErrorBanner } from '../../components';

interface Prompt { promptId: string; name: string; version: string; }
interface Model { modelId: string; name: string; }
interface ApiKey { keyId: string; name: string; prefix: string; }
interface Check { type: string; expected: string; }
interface CheckResult { type: string; expected: string; passed: boolean; message: string; }
interface Suite { evaluationId: string; name: string; description: string; promptId: string; promptVersion: number; promptName: string; caseCount: number; createdAt: string; updatedAt: string; cases?: EvalCase[]; }
interface EvalCase { caseId: string; name: string; position: number; variablesJson: string; checks: Check[]; }
interface RunCase { resultId: string; caseId: string; caseName: string; status: string; completion: string; checkResults: CheckResult[]; inputTokens: number; outputTokens: number; latencyMs: number; costMinor: number; currency: string; errorCode: number; errorMessage: string; }
interface Run { runId: string; status: string; modelId: string; modelName: string; promptVersion: number; caseCount: number; completedCount: number; passedCount: number; failedCount: number; errorCount: number; cancelledCount: number; totalCostMinor: number; currency: string; medianLatencyMs: number; createdAt: string; completedAt: string; cases?: RunCase[]; }
interface CaseComparison { caseId: string; caseName: string; left?: RunCase; right?: RunCase; onlyInLeft: boolean; onlyInRight: boolean; }
interface Comparison { left: Run; right: Run; passRateDeltaMilli: number; costDeltaMinor: number; medianLatencyDeltaMs: number; cases: CaseComparison[]; }

const RUN_POLL_MS = 2000;

function formatMinor(minor: number, currency: string): string {
  const units: Record<string, number> = { USD: 100, CNY: 100, EUR: 100 };
  const factor = units[currency] || 100;
  return `${(minor / factor).toFixed(4)} ${currency || 'USD'}`;
}

export default function UserEvaluationsPage() {
  const api = useApi(); const { orgId } = useOrg(); const { t } = useI18n();
  const [rows, setRows] = useState<Suite[]>([]); const [prompts, setPrompts] = useState<Prompt[]>([]);
  const [error, setError] = useState(''); const [open, setOpen] = useState(false);
  const [name, setName] = useState(''); const [description, setDescription] = useState('');
  const [promptId, setPromptId] = useState(''); const [version, setVersion] = useState(''); const [versions, setVersions] = useState<number[]>([]);
  const load = () => api.get<{ evaluations?: Suite[] }>('/api/v1/evaluations?page.limit=100', orgId).then((data) => setRows(data.evaluations || [])).catch((e) => setError(e.message));
  useEffect(() => { void load(); api.get<{ prompts?: Prompt[] }>('/api/v1/prompts?page.limit=100', orgId).then((data) => setPrompts(data.prompts || [])).catch(() => {}); }, [api, orgId]);
  useEffect(() => { if (!promptId) { setVersions([]); return; } api.get<{ versions?: { version: number }[] }>(`/api/v1/prompts/${promptId}/versions?page.limit=100`, orgId).then((data) => setVersions((data.versions || []).map((v) => Number(v.version)))).catch((e) => setError(e.message)); }, [api, orgId, promptId]);
  const create = async () => { try { const data = await api.post<{ evaluation: Suite }>('/api/v1/evaluations', orgId, { name, description, promptId, promptVersion: Number(version) }); setOpen(false); navigate(`/evaluations/${data.evaluation.evaluationId}`); } catch (e) { setError(e instanceof Error ? e.message : t('evaluations.loadFailed')); } };
  const remove = async (id: string) => { try { await api.del(`/api/v1/evaluations/${id}`, orgId); await load(); } catch (e) { setError(e instanceof Error ? e.message : t('evaluations.loadFailed')); } };
  return <div className="page" data-testid="evaluations-page">
    <div className="page-header"><div><h1>{t('evaluations.title')}</h1><p className="muted">{t('evaluations.subtitle')}</p></div><button data-testid="new-evaluation" onClick={() => setOpen(true)}>{t('evaluations.new')}</button></div>
    {error && <ErrorBanner message={error} />}
    {rows.length === 0 ? <div className="empty" data-testid="evaluations-empty">{t('evaluations.empty')}</div> : <table className="table" data-testid="evaluations-table"><thead><tr><th>{t('common.name')}</th><th>{t('evaluations.prompt')}</th><th>{t('evaluations.version')}</th><th>{t('evaluations.cases')}</th><th>{t('common.updated')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.evaluationId} data-testid={`evaluation-row-${row.evaluationId}`}><td><button className="link" onClick={() => navigate(`/evaluations/${row.evaluationId}`)}>{row.name}</button></td><td>{row.promptName || row.promptId}</td><td>{row.promptVersion}</td><td>{row.caseCount}</td><td>{row.updatedAt}</td><td><button className="link danger" data-testid={`delete-evaluation-${row.evaluationId}`} onClick={() => void remove(row.evaluationId)}>{t('common.delete')}</button></td></tr>)}</tbody></table>}
    {open && <Dialog title={t('evaluations.createTitle')} testId="create-evaluation-dialog" onClose={() => setOpen(false)}><div className="form-grid"><div className="form-field full"><label htmlFor="evaluation-name">{t('common.name')}</label><input id="evaluation-name" data-testid="evaluation-name" maxLength={128} value={name} onChange={(e) => setName(e.target.value)} /></div><div className="form-field full"><label htmlFor="evaluation-prompt">{t('evaluations.prompt')}</label><select id="evaluation-prompt" data-testid="evaluation-prompt" value={promptId} onChange={(e) => { setPromptId(e.target.value); setVersion(''); }}><option value="">{t('evaluations.choosePrompt')}</option>{prompts.map((p) => <option key={p.promptId} value={p.promptId}>{p.name}</option>)}</select></div><div className="form-field"><label htmlFor="evaluation-version">{t('evaluations.version')}</label><select id="evaluation-version" data-testid="evaluation-version" value={version} onChange={(e) => setVersion(e.target.value)}><option value="">{t('evaluations.chooseVersion')}</option>{versions.map((v) => <option key={v} value={v}>{v}</option>)}</select></div><div className="form-field full"><label htmlFor="evaluation-description">{t('common.descriptionOptional')}</label><textarea id="evaluation-description" data-testid="evaluation-description" maxLength={500} value={description} onChange={(e) => setDescription(e.target.value)} /></div></div><div className="dialog-actions"><button className="secondary" onClick={() => setOpen(false)}>{t('common.cancel')}</button><button data-testid="submit-evaluation" disabled={!name.trim() || !promptId || !version} onClick={() => void create()}>{t('evaluations.create')}</button></div></Dialog>}
  </div>;
}

export function UserEvaluationDetailPage() {
  const api = useApi(); const { orgId } = useOrg(); const { t } = useI18n(); const { evaluationId = '' } = useParams();
  const [suite, setSuite] = useState<Suite | null>(null); const [runs, setRuns] = useState<Run[]>([]); const [error, setError] = useState(''); const [addOpen, setAddOpen] = useState(false);
  const [caseName, setCaseName] = useState(''); const [variables, setVariables] = useState('{}'); const [checkType, setCheckType] = useState('contains'); const [expected, setExpected] = useState('');
  const [runOpen, setRunOpen] = useState(false); const [models, setModels] = useState<Model[]>([]); const [keys, setKeys] = useState<ApiKey[]>([]); const [modelId, setModelId] = useState(''); const [apiKeyId, setApiKeyId] = useState(''); const [runBusy, setRunBusy] = useState(false);
  const load = () => api.get<{ evaluation: Suite }>(`/api/v1/evaluations/${evaluationId}`, orgId).then((data) => setSuite(data.evaluation)).catch((e) => setError(e.message));
  useEffect(() => { void load(); api.get<{ runs?: Run[] }>(`/api/v1/evaluations/${evaluationId}/runs?page.limit=100`, orgId).then((data) => setRuns(data.runs || [])).catch(() => {}); api.get<{ models?: Model[] }>('/api/v1/models?page.limit=100', orgId).then((data) => setModels(data.models || [])).catch(() => {}); api.get<{ keys?: ApiKey[] }>('/api/v1/auth/api-keys?active_only=true&page.limit=100', orgId).then((data) => setKeys(data.keys || [])).catch(() => {}); }, [api, orgId, evaluationId]);
  const addCase = async () => { try { const parsed = JSON.parse(variables) as Record<string, string>; await api.post(`/api/v1/evaluations/${evaluationId}/cases`, orgId, { name: caseName, variables: parsed, checks: [{ type: checkType, expected }] }); setAddOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : t('evaluations.caseInvalid')); } };
  const startRun = async () => { setRunBusy(true); setError(''); try { const data = await api.post<{ run: Run }>(`/api/v1/evaluations/${evaluationId}/runs`, orgId, { modelId, apiKeyId, promptVersion: suite?.promptVersion, caseIds: [] }); setRunOpen(false); navigate(`/evaluations/${evaluationId}/runs/${data.run.runId}`); } catch (e) { setError(e instanceof Error ? e.message : t('evaluations.runFailed')); } finally { setRunBusy(false); } };
  if (error && !suite) return <div className="page"><ErrorBanner message={error} /></div>;
  return <div className="page" data-testid="evaluation-detail-page"><div className="page-header"><div><h1>{suite?.name || t('common.loading')}</h1><p className="muted">{suite?.promptName} · v{suite?.promptVersion}</p></div><button data-testid="add-evaluation-case" onClick={() => setAddOpen(true)}>{t('evaluations.addCase')}</button></div>{error && <ErrorBanner message={error} />}
    <section className="section"><div className="section-header"><h2>{t('evaluations.testCases')}</h2><span>{suite?.caseCount || 0} / 50</span></div>{!suite?.cases?.length ? <div className="empty" data-testid="evaluation-cases-empty">{t('evaluations.noCases')}</div> : <table className="table" data-testid="evaluation-cases-table"><thead><tr><th>{t('common.name')}</th><th>{t('evaluations.variables')}</th><th>{t('evaluations.checks')}</th></tr></thead><tbody>{suite.cases.map((item) => <tr key={item.caseId} data-testid={`evaluation-case-${item.caseId}`}><td>{item.name}</td><td><code>{item.variablesJson}</code></td><td>{item.checks.map((c) => `${c.type}: ${c.expected}`).join(', ')}</td></tr>)}</tbody></table>}</section>
    <section className="section"><div className="section-header"><h2>{t('evaluations.runs')}</h2><button className="secondary" data-testid="run-evaluation" disabled={!suite?.caseCount} onClick={() => setRunOpen(true)}>{t('evaluations.run')}</button></div>{runs.length ? <table className="table" data-testid="evaluation-runs-table"><thead><tr><th>{t('common.created')}</th><th>{t('evaluations.model')}</th><th>{t('common.status')}</th><th>{t('evaluations.progress')}</th><th>{t('evaluations.passRate')}</th><th>{t('common.actions')}</th></tr></thead><tbody>{runs.map((run) => <tr key={run.runId} data-testid={`evaluation-run-row-${run.runId}`}><td><button className="link" onClick={() => navigate(`/evaluations/${evaluationId}/runs/${run.runId}`)}>{run.createdAt}</button></td><td>{run.modelName || run.modelId}</td><td>{run.status}</td><td>{run.completedCount}/{run.caseCount}</td><td>{run.caseCount ? `${Math.round((run.passedCount / run.caseCount) * 100)}%` : '—'}</td><td><button className="link" onClick={() => navigate(`/evaluations/${evaluationId}/compare?left=${run.runId}`)}>{t('evaluations.compare')}</button></td></tr>)}</tbody></table> : <div className="empty" data-testid="evaluation-runs-empty">{t('evaluations.noRuns')}</div>}</section>
    {addOpen && <Dialog title={t('evaluations.addCase')} testId="evaluation-case-dialog" onClose={() => setAddOpen(false)}><div className="form-grid"><div className="form-field full"><label htmlFor="case-name">{t('common.name')}</label><input id="case-name" data-testid="evaluation-case-name" maxLength={128} value={caseName} onChange={(e) => setCaseName(e.target.value)} /></div><div className="form-field full"><label htmlFor="case-variables">{t('evaluations.variables')}</label><textarea id="case-variables" data-testid="evaluation-case-variables" value={variables} onChange={(e) => setVariables(e.target.value)} /></div><div className="form-field"><label htmlFor="check-type">{t('evaluations.checkType')}</label><select id="check-type" data-testid="evaluation-check-type" value={checkType} onChange={(e) => setCheckType(e.target.value)}><option value="exact">{t('evaluations.exact')}</option><option value="contains">{t('evaluations.contains')}</option><option value="regex">{t('evaluations.regex')}</option><option value="valid_json">{t('evaluations.validJson')}</option></select></div><div className="form-field"><label htmlFor="check-expected">{t('evaluations.expected')}</label><input id="check-expected" data-testid="evaluation-check-expected" value={expected} onChange={(e) => setExpected(e.target.value)} /></div></div><div className="dialog-actions"><button className="secondary" onClick={() => setAddOpen(false)}>{t('common.cancel')}</button><button data-testid="save-evaluation-case" disabled={!caseName.trim() || (checkType !== 'valid_json' && !expected.trim())} onClick={() => void addCase()}>{t('common.save')}</button></div></Dialog>}
    {runOpen && <Dialog title={t('evaluations.runTitle')} testId="evaluation-run-dialog" onClose={() => setRunOpen(false)}><p>{t('evaluations.runConfirmation', { count: suite?.caseCount || 0 })}</p><div className="form-grid"><div className="form-field full"><label htmlFor="evaluation-model">{t('evaluations.model')}</label><select id="evaluation-model" data-testid="evaluation-model" value={modelId} onChange={(e) => setModelId(e.target.value)}><option value="">{t('evaluations.chooseModel')}</option>{models.map((m) => <option key={m.modelId} value={m.modelId}>{m.name}</option>)}</select></div><div className="form-field full"><label htmlFor="evaluation-api-key">{t('evaluations.apiKey')}</label><select id="evaluation-api-key" data-testid="evaluation-api-key" value={apiKeyId} onChange={(e) => setApiKeyId(e.target.value)}><option value="">{t('evaluations.chooseApiKey')}</option>{keys.map((key) => <option key={key.keyId} value={key.keyId}>{key.name} ({key.prefix})</option>)}</select></div></div><div className="dialog-actions"><button className="secondary" onClick={() => setRunOpen(false)}>{t('common.cancel')}</button><button data-testid="confirm-run-evaluation" disabled={!modelId || !apiKeyId || runBusy} onClick={() => void startRun()}>{runBusy ? t('common.working') : t('evaluations.run')}</button></div></Dialog>}
  </div>;
}

export function UserEvaluationRunPage() {
  const api = useApi(); const { orgId } = useOrg(); const { t } = useI18n(); const { evaluationId = '', runId = '' } = useParams();
  const [run, setRun] = useState<Run | null>(null); const [error, setError] = useState(''); const [cancelBusy, setCancelBusy] = useState(false);
  const pollRef = useRef<number | null>(null);
  const terminal = run ? run.status !== 'pending' && run.status !== 'running' : false;
  useEffect(() => {
    let cancelled = false;
    const fetchRun = () => api.get<{ run: Run }>(`/api/v1/evaluations/${evaluationId}/runs/${runId}`, orgId).then((data) => { if (!cancelled) { setRun(data.run); setError(''); } }).catch((e) => { if (!cancelled) setError(e.message); });
    void fetchRun();
    const timer = window.setInterval(() => { void fetchRun(); }, RUN_POLL_MS);
    pollRef.current = timer;
    return () => { cancelled = true; if (pollRef.current !== null) window.clearInterval(pollRef.current); };
  }, [api, orgId, evaluationId, runId]);
  useEffect(() => { if (terminal && pollRef.current !== null) { window.clearInterval(pollRef.current); pollRef.current = null; } }, [terminal]);
  const cancel = async () => { setCancelBusy(true); try { await api.post(`/api/v1/evaluations/${evaluationId}/runs/${runId}:cancel`, orgId, {}); const data = await api.get<{ run: Run }>(`/api/v1/evaluations/${evaluationId}/runs/${runId}`, orgId); setRun(data.run); } catch (e) { setError(e instanceof Error ? e.message : t('evaluations.cancelFailed')); } finally { setCancelBusy(false); } };
  const passRate = run && run.caseCount > 0 ? `${Math.round((run.passedCount / run.caseCount) * 100)}%` : '—';
  return <div className="page" data-testid="evaluation-run-page">
    <div className="page-header"><div><h1>{t('evaluations.runResults')}</h1><p className="muted" data-testid="evaluation-run-status">{run ? `${run.status} · ${run.completedCount}/${run.caseCount}` : t('common.loading')}</p></div><div className="header-actions">{run && !terminal && <button className="secondary" data-testid="cancel-evaluation-run" disabled={cancelBusy} onClick={() => void cancel()}>{cancelBusy ? t('common.working') : t('evaluations.cancel')}</button>}<button className="secondary" onClick={() => navigate(`/evaluations/${evaluationId}/compare?left=${runId}`)}>{t('evaluations.compare')}</button><button className="secondary" onClick={() => navigate(`/evaluations/${evaluationId}`)}>{t('evaluations.backToEvaluation')}</button></div></div>
    {error && <ErrorBanner message={error} />}
    {run && <section className="section" data-testid="evaluation-run-summary"><div className="stats-grid">
      <div className="stat"><span className="stat-label">{t('evaluations.passRate')}</span><span className="stat-value" data-testid="evaluation-run-pass-rate">{passRate}</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.totalCost')}</span><span className="stat-value" data-testid="evaluation-run-total-cost">{formatMinor(run.totalCostMinor, run.currency)}</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.medianLatency')}</span><span className="stat-value" data-testid="evaluation-run-median-latency">{run.medianLatencyMs ? `${run.medianLatencyMs} ms` : '—'}</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.passed')}</span><span className="stat-value">{run.passedCount}</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.failed')}</span><span className="stat-value">{run.failedCount}</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.errorMessage')}</span><span className="stat-value">{run.errorCount}</span></div>
    </div></section>}
    {run && <section className="section"><div className="section-header"><h2>{t('evaluations.testCases')}</h2></div>{!run.cases?.length ? <div className="empty" data-testid="evaluation-run-results-empty">{t('evaluations.noCases')}</div> : <table className="table" data-testid="evaluation-run-results"><thead><tr><th>{t('common.name')}</th><th>{t('common.status')}</th><th>{t('evaluations.output')}</th><th>{t('evaluations.checkResults')}</th><th>{t('evaluations.inputTokens')}</th><th>{t('evaluations.outputTokens')}</th><th>{t('evaluations.latency')}</th><th>{t('evaluations.cost')}</th></tr></thead><tbody>{run.cases.map((item) => <tr key={item.resultId || item.caseId} data-testid={`evaluation-run-case-${item.caseId}`}><td>{item.caseName}</td><td data-testid={`evaluation-run-case-status-${item.caseId}`}>{item.status}</td><td className="mono">{item.completion || (item.errorMessage ? <span className="danger" title={item.errorMessage}>{item.errorMessage}</span> : '—')}</td><td>{(item.checkResults || []).map((c, i) => <span key={i} className={c.passed ? 'ok' : 'danger'}>{c.type}: {c.passed ? t('evaluations.passed') : t('evaluations.failed')}</span>)}</td><td>{item.inputTokens}</td><td>{item.outputTokens}</td><td>{item.latencyMs ? `${item.latencyMs} ms` : '—'}</td><td>{item.costMinor ? formatMinor(item.costMinor, item.currency) : '—'}</td></tr>)}</tbody></table>}</section>}
  </div>;
}

export function UserEvaluationComparePage() {
  const api = useApi(); const { orgId } = useOrg(); const { t } = useI18n(); const { evaluationId = '' } = useParams();
  const [runs, setRuns] = useState<Run[]>([]); const [left, setLeft] = useState(''); const [right, setRight] = useState('');
  const [comparison, setComparison] = useState<Comparison | null>(null); const [error, setError] = useState('');
  useEffect(() => { const params = new URLSearchParams(location.search); setLeft(params.get('left') || ''); setRight(params.get('right') || ''); api.get<{ runs?: Run[] }>(`/api/v1/evaluations/${evaluationId}/runs?page.limit=100`, orgId).then((data) => setRuns(data.runs || [])).catch((e) => setError(e.message)); }, [api, orgId, evaluationId]);
  const compare = async () => { setError(''); setComparison(null); try { const data = await api.post<Comparison>(`/api/v1/evaluations/${evaluationId}/runs:compare`, orgId, { leftRunId: left, rightRunId: right }); setComparison(data); } catch (e) { setError(e instanceof Error ? e.message : t('evaluations.compareFailed')); } };
  useEffect(() => { if (left && right) void compare(); }, [left, right]);
  return <div className="page" data-testid="evaluation-compare-page">
    <div className="page-header"><div><h1>{t('evaluations.compare')}</h1><p className="muted">{t('evaluations.chooseTwoRuns')}</p></div><button className="secondary" onClick={() => navigate(`/evaluations/${evaluationId}`)}>{t('evaluations.backToEvaluation')}</button></div>
    {error && <ErrorBanner message={error} />}
    <section className="section"><div className="form-grid">
      <div className="form-field"><label htmlFor="compare-left">{t('evaluations.leftRun')}</label><select id="compare-left" data-testid="compare-left-run" value={left} onChange={(e) => setLeft(e.target.value)}><option value="">{t('evaluations.chooseTwoRuns')}</option>{runs.map((r) => <option key={r.runId} value={r.runId}>{r.createdAt} · {r.status}</option>)}</select></div>
      <div className="form-field"><label htmlFor="compare-right">{t('evaluations.rightRun')}</label><select id="compare-right" data-testid="compare-right-run" value={right} onChange={(e) => setRight(e.target.value)}><option value="">{t('evaluations.chooseTwoRuns')}</option>{runs.map((r) => <option key={r.runId} value={r.runId}>{r.createdAt} · {r.status}</option>)}</select></div>
    </div><div className="dialog-actions"><button data-testid="compare-runs" disabled={!left || !right || left === right} onClick={() => void compare()}>{t('evaluations.compared')}</button></div></section>
    {comparison && <><section className="section" data-testid="evaluation-compare-summary"><div className="stats-grid">
      <div className="stat"><span className="stat-label">{t('evaluations.passRateDelta')}</span><span className="stat-value" data-testid="compare-pass-rate-delta">{(comparison.passRateDeltaMilli / 10).toFixed(1)}%</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.costDelta')}</span><span className="stat-value" data-testid="compare-cost-delta">{formatMinor(comparison.costDeltaMinor, comparison.right?.currency || comparison.left?.currency || 'USD')}</span></div>
      <div className="stat"><span className="stat-label">{t('evaluations.latencyDelta')}</span><span className="stat-value" data-testid="compare-latency-delta">{comparison.medianLatencyDeltaMs} ms</span></div>
    </div></section>
    <section className="section"><div className="section-header"><h2>{t('evaluations.testCases')}</h2></div><table className="table" data-testid="evaluation-compare-cases"><thead><tr><th>{t('common.name')}</th><th>{t('evaluations.leftRun')}</th><th>{t('evaluations.rightRun')}</th></tr></thead><tbody>{comparison.cases.map((item) => <tr key={item.caseId} data-testid={`compare-case-${item.caseId}`}><td>{item.caseName}{item.onlyInLeft && <span className="muted"> · {t('evaluations.onlyInLeft')}</span>}{item.onlyInRight && <span className="muted"> · {t('evaluations.onlyInRight')}</span>}</td><td className="mono">{item.left ? `${item.left.status} · ${item.left.completion || item.left.errorMessage || '—'}` : '—'}</td><td className="mono">{item.right ? `${item.right.status} · ${item.right.completion || item.right.errorMessage || '—'}` : '—'}</td></tr>)}</tbody></table></section></>}
  </div>;
}
