// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: taas/image/v1/image.proto

package imagev1

import (
	v1 "github.com/go-taas/go-taas/proto/taas/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterImageRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag    string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	// accelerator names the hardware platform the image runs on.
	Accelerator string `protobuf:"bytes,4,opt,name=accelerator,proto3" json:"accelerator,omitempty"`
	// engine names the inference engine (vllm, sglang, ...).
	Engine        string `protobuf:"bytes,5,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterImageRequest) Reset() {
	*x = RegisterImageRequest{}
	mi := &file_taas_image_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterImageRequest) ProtoMessage() {}

func (x *RegisterImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterImageRequest.ProtoReflect.Descriptor instead.
func (*RegisterImageRequest) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterImageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterImageRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RegisterImageRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegisterImageRequest) GetAccelerator() string {
	if x != nil {
		return x.Accelerator
	}
	return ""
}

func (x *RegisterImageRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type RegisterImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ImageId       string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterImageResponse) Reset() {
	*x = RegisterImageResponse{}
	mi := &file_taas_image_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterImageResponse) ProtoMessage() {}

func (x *RegisterImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterImageResponse.ProtoReflect.Descriptor instead.
func (*RegisterImageResponse) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterImageResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Accelerator   string                 `protobuf:"bytes,2,opt,name=accelerator,proto3" json:"accelerator,omitempty"`
	Engine        string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_taas_image_v1_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{2}
}

func (x *ListImagesRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListImagesRequest) GetAccelerator() string {
	if x != nil {
		return x.Accelerator
	}
	return ""
}

func (x *ListImagesRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Images        []*ImageSummary        `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	PageMeta      *v1.PageMeta           `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_taas_image_v1_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{3}
}

func (x *ListImagesResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListImagesResponse) GetImages() []*ImageSummary {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ListImagesResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type ImageSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest        string                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Accelerator   string                 `protobuf:"bytes,5,opt,name=accelerator,proto3" json:"accelerator,omitempty"`
	Engine        string                 `protobuf:"bytes,6,opt,name=engine,proto3" json:"engine,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSummary) Reset() {
	*x = ImageSummary{}
	mi := &file_taas_image_v1_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSummary) ProtoMessage() {}

func (x *ImageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSummary.ProtoReflect.Descriptor instead.
func (*ImageSummary) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{4}
}

func (x *ImageSummary) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageSummary) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ImageSummary) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImageSummary) GetAccelerator() string {
	if x != nil {
		return x.Accelerator
	}
	return ""
}

func (x *ImageSummary) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ImageSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type TriggerWarmupRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ImageId string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// node_selector restricts the warmup to nodes matching the labels.
	NodeSelector  map[string]string `protobuf:"bytes,2,rep,name=node_selector,json=nodeSelector,proto3" json:"node_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWarmupRequest) Reset() {
	*x = TriggerWarmupRequest{}
	mi := &file_taas_image_v1_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWarmupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWarmupRequest) ProtoMessage() {}

func (x *TriggerWarmupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWarmupRequest.ProtoReflect.Descriptor instead.
func (*TriggerWarmupRequest) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerWarmupRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *TriggerWarmupRequest) GetNodeSelector() map[string]string {
	if x != nil {
		return x.NodeSelector
	}
	return nil
}

type TriggerWarmupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWarmupResponse) Reset() {
	*x = TriggerWarmupResponse{}
	mi := &file_taas_image_v1_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWarmupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWarmupResponse) ProtoMessage() {}

func (x *TriggerWarmupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_image_v1_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWarmupResponse.ProtoReflect.Descriptor instead.
func (*TriggerWarmupResponse) Descriptor() ([]byte, []int) {
	return file_taas_image_v1_image_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerWarmupResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TriggerWarmupResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_taas_image_v1_image_proto protoreflect.FileDescriptor

const file_taas_image_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x19taas/image/v1/image.proto\x12\rtaas.image.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1btaas/common/v1/common.proto\"\x8e\x01\n" +
	"\x14RegisterImageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\x12 \n" +
	"\vaccelerator\x18\x04 \x01(\tR\vaccelerator\x12\x16\n" +
	"\x06engine\x18\x05 \x01(\tR\x06engine\"h\n" +
	"\x15RegisterImageResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\"~\n" +
	"\x11ListImagesRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\x12 \n" +
	"\vaccelerator\x18\x02 \x01(\tR\vaccelerator\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\"\xb6\x01\n" +
	"\x12ListImagesResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x123\n" +
	"\x06images\x18\x02 \x03(\v2\x1b.taas.image.v1.ImageSummaryR\x06images\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xc0\x01\n" +
	"\fImageSummary\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\tR\x06digest\x12 \n" +
	"\vaccelerator\x18\x05 \x01(\tR\vaccelerator\x12\x16\n" +
	"\x06engine\x18\x06 \x01(\tR\x06engine\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xce\x01\n" +
	"\x14TriggerWarmupRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12Z\n" +
	"\rnode_selector\x18\x02 \x03(\v25.taas.image.v1.TriggerWarmupRequest.NodeSelectorEntryR\fnodeSelector\x1a?\n" +
	"\x11NodeSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x15TriggerWarmupResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId2\xfa\x02\n" +
	"\fImageService\x12u\n" +
	"\rRegisterImage\x12#.taas.image.v1.RegisterImageRequest\x1a$.taas.image.v1.RegisterImageResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/images\x12i\n" +
	"\n" +
	"ListImages\x12 .taas.image.v1.ListImagesRequest\x1a!.taas.image.v1.ListImagesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/images\x12\x87\x01\n" +
	"\rTriggerWarmup\x12#.taas.image.v1.TriggerWarmupRequest\x1a$.taas.image.v1.TriggerWarmupResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/images/{image_id}:warmupB\xad\x01\n" +
	"\x11com.taas.image.v1B\n" +
	"ImageProtoP\x01Z6github.com/go-taas/go-taas/proto/taas/image/v1;imagev1\xa2\x02\x03TIX\xaa\x02\rTaas.Image.V1\xca\x02\rTaas\\Image\\V1\xe2\x02\x19Taas\\Image\\V1\\GPBMetadata\xea\x02\x0fTaas::Image::V1b\x06proto3"

var (
	file_taas_image_v1_image_proto_rawDescOnce sync.Once
	file_taas_image_v1_image_proto_rawDescData []byte
)

func file_taas_image_v1_image_proto_rawDescGZIP() []byte {
	file_taas_image_v1_image_proto_rawDescOnce.Do(func() {
		file_taas_image_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taas_image_v1_image_proto_rawDesc), len(file_taas_image_v1_image_proto_rawDesc)))
	})
	return file_taas_image_v1_image_proto_rawDescData
}

var file_taas_image_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_taas_image_v1_image_proto_goTypes = []any{
	(*RegisterImageRequest)(nil),  // 0: taas.image.v1.RegisterImageRequest
	(*RegisterImageResponse)(nil), // 1: taas.image.v1.RegisterImageResponse
	(*ListImagesRequest)(nil),     // 2: taas.image.v1.ListImagesRequest
	(*ListImagesResponse)(nil),    // 3: taas.image.v1.ListImagesResponse
	(*ImageSummary)(nil),          // 4: taas.image.v1.ImageSummary
	(*TriggerWarmupRequest)(nil),  // 5: taas.image.v1.TriggerWarmupRequest
	(*TriggerWarmupResponse)(nil), // 6: taas.image.v1.TriggerWarmupResponse
	nil,                           // 7: taas.image.v1.TriggerWarmupRequest.NodeSelectorEntry
	(*v1.Response)(nil),           // 8: taas.common.v1.Response
	(*v1.PageRequest)(nil),        // 9: taas.common.v1.PageRequest
	(*v1.PageMeta)(nil),           // 10: taas.common.v1.PageMeta
}
var file_taas_image_v1_image_proto_depIdxs = []int32{
	8,  // 0: taas.image.v1.RegisterImageResponse.response:type_name -> taas.common.v1.Response
	9,  // 1: taas.image.v1.ListImagesRequest.page:type_name -> taas.common.v1.PageRequest
	8,  // 2: taas.image.v1.ListImagesResponse.response:type_name -> taas.common.v1.Response
	4,  // 3: taas.image.v1.ListImagesResponse.images:type_name -> taas.image.v1.ImageSummary
	10, // 4: taas.image.v1.ListImagesResponse.page_meta:type_name -> taas.common.v1.PageMeta
	7,  // 5: taas.image.v1.TriggerWarmupRequest.node_selector:type_name -> taas.image.v1.TriggerWarmupRequest.NodeSelectorEntry
	8,  // 6: taas.image.v1.TriggerWarmupResponse.response:type_name -> taas.common.v1.Response
	0,  // 7: taas.image.v1.ImageService.RegisterImage:input_type -> taas.image.v1.RegisterImageRequest
	2,  // 8: taas.image.v1.ImageService.ListImages:input_type -> taas.image.v1.ListImagesRequest
	5,  // 9: taas.image.v1.ImageService.TriggerWarmup:input_type -> taas.image.v1.TriggerWarmupRequest
	1,  // 10: taas.image.v1.ImageService.RegisterImage:output_type -> taas.image.v1.RegisterImageResponse
	3,  // 11: taas.image.v1.ImageService.ListImages:output_type -> taas.image.v1.ListImagesResponse
	6,  // 12: taas.image.v1.ImageService.TriggerWarmup:output_type -> taas.image.v1.TriggerWarmupResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_taas_image_v1_image_proto_init() }
func file_taas_image_v1_image_proto_init() {
	if File_taas_image_v1_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taas_image_v1_image_proto_rawDesc), len(file_taas_image_v1_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taas_image_v1_image_proto_goTypes,
		DependencyIndexes: file_taas_image_v1_image_proto_depIdxs,
		MessageInfos:      file_taas_image_v1_image_proto_msgTypes,
	}.Build()
	File_taas_image_v1_image_proto = out.File
	file_taas_image_v1_image_proto_goTypes = nil
	file_taas_image_v1_image_proto_depIdxs = nil
}
