// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: taas/model/v1/model.proto

package modelv1

import (
	v1 "github.com/go-taas/go-taas/proto/taas/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterModelRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// weight_path is the object-storage path of the model weights, mounted
	// by inference pods through the shared filesystem.
	WeightPath    string `protobuf:"bytes,3,opt,name=weight_path,json=weightPath,proto3" json:"weight_path,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelRequest) Reset() {
	*x = RegisterModelRequest{}
	mi := &file_taas_model_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelRequest) ProtoMessage() {}

func (x *RegisterModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelRequest.ProtoReflect.Descriptor instead.
func (*RegisterModelRequest) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterModelRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterModelRequest) GetWeightPath() string {
	if x != nil {
		return x.WeightPath
	}
	return ""
}

func (x *RegisterModelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterModelResponse) Reset() {
	*x = RegisterModelResponse{}
	mi := &file_taas_model_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterModelResponse) ProtoMessage() {}

func (x *RegisterModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterModelResponse.ProtoReflect.Descriptor instead.
func (*RegisterModelResponse) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterModelResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterModelResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_taas_model_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Models        []*ModelSummary        `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	PageMeta      *v1.PageMeta           `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_taas_model_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *ListModelsResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListModelsResponse) GetModels() []*ModelSummary {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type ModelSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LatestVersion string                 `protobuf:"bytes,3,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	WeightPath    string                 `protobuf:"bytes,4,opt,name=weight_path,json=weightPath,proto3" json:"weight_path,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelSummary) Reset() {
	*x = ModelSummary{}
	mi := &file_taas_model_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSummary) ProtoMessage() {}

func (x *ModelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSummary.ProtoReflect.Descriptor instead.
func (*ModelSummary) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *ModelSummary) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelSummary) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

func (x *ModelSummary) GetWeightPath() string {
	if x != nil {
		return x.WeightPath
	}
	return ""
}

func (x *ModelSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_taas_model_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Model         *ModelSummary          `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Versions      []string               `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_taas_model_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetModelResponse) GetModel() *ModelSummary {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *GetModelResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_taas_model_v1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_taas_model_v1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_model_v1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_taas_model_v1_model_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteModelResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_taas_model_v1_model_proto protoreflect.FileDescriptor

const file_taas_model_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x19taas/model/v1/model.proto\x12\rtaas.model.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1btaas/common/v1/common.proto\"\x87\x01\n" +
	"\x14RegisterModelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vweight_path\x18\x03 \x01(\tR\n" +
	"weightPath\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"h\n" +
	"\x15RegisterModelResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"D\n" +
	"\x11ListModelsRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\"\xb6\x01\n" +
	"\x12ListModelsResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x123\n" +
	"\x06models\x18\x02 \x03(\v2\x1b.taas.model.v1.ModelSummaryR\x06models\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xa4\x01\n" +
	"\fModelSummary\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0elatest_version\x18\x03 \x01(\tR\rlatestVersion\x12\x1f\n" +
	"\vweight_path\x18\x04 \x01(\tR\n" +
	"weightPath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\",\n" +
	"\x0fGetModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\x97\x01\n" +
	"\x10GetModelResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x121\n" +
	"\x05model\x18\x02 \x01(\v2\x1b.taas.model.v1.ModelSummaryR\x05model\x12\x1a\n" +
	"\bversions\x18\x03 \x03(\tR\bversions\"/\n" +
	"\x12DeleteModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"K\n" +
	"\x13DeleteModelResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse2\xd9\x03\n" +
	"\fModelService\x12u\n" +
	"\rRegisterModel\x12#.taas.model.v1.RegisterModelRequest\x1a$.taas.model.v1.RegisterModelResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/models\x12i\n" +
	"\n" +
	"ListModels\x12 .taas.model.v1.ListModelsRequest\x1a!.taas.model.v1.ListModelsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/models\x12n\n" +
	"\bGetModel\x12\x1e.taas.model.v1.GetModelRequest\x1a\x1f.taas.model.v1.GetModelResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/models/{model_id}\x12w\n" +
	"\vDeleteModel\x12!.taas.model.v1.DeleteModelRequest\x1a\".taas.model.v1.DeleteModelResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/v1/models/{model_id}B\xad\x01\n" +
	"\x11com.taas.model.v1B\n" +
	"ModelProtoP\x01Z6github.com/go-taas/go-taas/proto/taas/model/v1;modelv1\xa2\x02\x03TMX\xaa\x02\rTaas.Model.V1\xca\x02\rTaas\\Model\\V1\xe2\x02\x19Taas\\Model\\V1\\GPBMetadata\xea\x02\x0fTaas::Model::V1b\x06proto3"

var (
	file_taas_model_v1_model_proto_rawDescOnce sync.Once
	file_taas_model_v1_model_proto_rawDescData []byte
)

func file_taas_model_v1_model_proto_rawDescGZIP() []byte {
	file_taas_model_v1_model_proto_rawDescOnce.Do(func() {
		file_taas_model_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taas_model_v1_model_proto_rawDesc), len(file_taas_model_v1_model_proto_rawDesc)))
	})
	return file_taas_model_v1_model_proto_rawDescData
}

var file_taas_model_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_taas_model_v1_model_proto_goTypes = []any{
	(*RegisterModelRequest)(nil),  // 0: taas.model.v1.RegisterModelRequest
	(*RegisterModelResponse)(nil), // 1: taas.model.v1.RegisterModelResponse
	(*ListModelsRequest)(nil),     // 2: taas.model.v1.ListModelsRequest
	(*ListModelsResponse)(nil),    // 3: taas.model.v1.ListModelsResponse
	(*ModelSummary)(nil),          // 4: taas.model.v1.ModelSummary
	(*GetModelRequest)(nil),       // 5: taas.model.v1.GetModelRequest
	(*GetModelResponse)(nil),      // 6: taas.model.v1.GetModelResponse
	(*DeleteModelRequest)(nil),    // 7: taas.model.v1.DeleteModelRequest
	(*DeleteModelResponse)(nil),   // 8: taas.model.v1.DeleteModelResponse
	(*v1.Response)(nil),           // 9: taas.common.v1.Response
	(*v1.PageRequest)(nil),        // 10: taas.common.v1.PageRequest
	(*v1.PageMeta)(nil),           // 11: taas.common.v1.PageMeta
}
var file_taas_model_v1_model_proto_depIdxs = []int32{
	9,  // 0: taas.model.v1.RegisterModelResponse.response:type_name -> taas.common.v1.Response
	10, // 1: taas.model.v1.ListModelsRequest.page:type_name -> taas.common.v1.PageRequest
	9,  // 2: taas.model.v1.ListModelsResponse.response:type_name -> taas.common.v1.Response
	4,  // 3: taas.model.v1.ListModelsResponse.models:type_name -> taas.model.v1.ModelSummary
	11, // 4: taas.model.v1.ListModelsResponse.page_meta:type_name -> taas.common.v1.PageMeta
	9,  // 5: taas.model.v1.GetModelResponse.response:type_name -> taas.common.v1.Response
	4,  // 6: taas.model.v1.GetModelResponse.model:type_name -> taas.model.v1.ModelSummary
	9,  // 7: taas.model.v1.DeleteModelResponse.response:type_name -> taas.common.v1.Response
	0,  // 8: taas.model.v1.ModelService.RegisterModel:input_type -> taas.model.v1.RegisterModelRequest
	2,  // 9: taas.model.v1.ModelService.ListModels:input_type -> taas.model.v1.ListModelsRequest
	5,  // 10: taas.model.v1.ModelService.GetModel:input_type -> taas.model.v1.GetModelRequest
	7,  // 11: taas.model.v1.ModelService.DeleteModel:input_type -> taas.model.v1.DeleteModelRequest
	1,  // 12: taas.model.v1.ModelService.RegisterModel:output_type -> taas.model.v1.RegisterModelResponse
	3,  // 13: taas.model.v1.ModelService.ListModels:output_type -> taas.model.v1.ListModelsResponse
	6,  // 14: taas.model.v1.ModelService.GetModel:output_type -> taas.model.v1.GetModelResponse
	8,  // 15: taas.model.v1.ModelService.DeleteModel:output_type -> taas.model.v1.DeleteModelResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_taas_model_v1_model_proto_init() }
func file_taas_model_v1_model_proto_init() {
	if File_taas_model_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taas_model_v1_model_proto_rawDesc), len(file_taas_model_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taas_model_v1_model_proto_goTypes,
		DependencyIndexes: file_taas_model_v1_model_proto_depIdxs,
		MessageInfos:      file_taas_model_v1_model_proto_msgTypes,
	}.Build()
	File_taas_model_v1_model_proto = out.File
	file_taas_model_v1_model_proto_goTypes = nil
	file_taas_model_v1_model_proto_depIdxs = nil
}
