// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: taas/auth/v1/auth.proto

package authv1

import (
	v1 "github.com/go-taas/go-taas/proto/taas/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Organization  string                 `protobuf:"bytes,4,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ListAPIKeysRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Keys          []*APIKeySummary       `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	PageMeta      *v1.PageMeta           `protobuf:"bytes,3,opt,name=page_meta,json=pageMeta,proto3" json:"page_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ListAPIKeysResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ListAPIKeysResponse) GetKeys() []*APIKeySummary {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListAPIKeysResponse) GetPageMeta() *v1.PageMeta {
	if x != nil {
		return x.PageMeta
	}
	return nil
}

type APIKeySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Revoked       bool                   `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeySummary) Reset() {
	*x = APIKeySummary{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeySummary) ProtoMessage() {}

func (x *APIKeySummary) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeySummary.ProtoReflect.Descriptor instead.
func (*APIKeySummary) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *APIKeySummary) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *APIKeySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeySummary) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *APIKeySummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *APIKeySummary) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *APIKeySummary) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CreateAPIKeyResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Response *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// api_key carries the plaintext key. It is shown exactly once at
	// creation time and never stored or returned again.
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	KeyId         string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAPIKeyResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateAPIKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type RevokeAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyRequest) Reset() {
	*x = RevokeAPIKeyRequest{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyRequest) ProtoMessage() {}

func (x *RevokeAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeAPIKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type RevokeAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyResponse) Reset() {
	*x = RevokeAPIKeyResponse{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyResponse) ProtoMessage() {}

func (x *RevokeAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAPIKeyResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type VerifyAPIKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key_digest is the salted hash digest of the API key, not the key
	// itself: the gateway never forwards plaintext keys.
	KeyDigest     string `protobuf:"bytes,1,opt,name=key_digest,json=keyDigest,proto3" json:"key_digest,omitempty"`
	Model         string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SourceIp      string `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAPIKeyRequest) Reset() {
	*x = VerifyAPIKeyRequest{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAPIKeyRequest) ProtoMessage() {}

func (x *VerifyAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*VerifyAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyAPIKeyRequest) GetKeyDigest() string {
	if x != nil {
		return x.KeyDigest
	}
	return ""
}

func (x *VerifyAPIKeyRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *VerifyAPIKeyRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

type VerifyAPIKeyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Response       *v1.Response           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	KeyId          string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyAPIKeyResponse) Reset() {
	*x = VerifyAPIKeyResponse{}
	mi := &file_taas_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAPIKeyResponse) ProtoMessage() {}

func (x *VerifyAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taas_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*VerifyAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_taas_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyAPIKeyResponse) GetResponse() *v1.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *VerifyAPIKeyResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *VerifyAPIKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *VerifyAPIKeyResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_taas_auth_v1_auth_proto protoreflect.FileDescriptor

const file_taas_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x17taas/auth/v1/auth.proto\x12\ftaas.auth.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1btaas/common/v1/common.proto\"\x85\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\"\n" +
	"\forganization\x18\x04 \x01(\tR\forganization\"c\n" +
	"\x12CreateUserResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x89\x01\n" +
	"\rLoginResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"E\n" +
	"\x12ListAPIKeysRequest\x12/\n" +
	"\x04page\x18\x01 \x01(\v2\x1b.taas.common.v1.PageRequestR\x04page\"\xb3\x01\n" +
	"\x13ListAPIKeysResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12/\n" +
	"\x04keys\x18\x02 \x03(\v2\x1b.taas.auth.v1.APIKeySummaryR\x04keys\x125\n" +
	"\tpage_meta\x18\x03 \x01(\v2\x18.taas.common.v1.PageMetaR\bpageMeta\"\xaa\x01\n" +
	"\rAPIKeySummary\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\arevoked\x18\x06 \x01(\bR\arevoked\"H\n" +
	"\x13CreateAPIKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"|\n" +
	"\x14CreateAPIKeyResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\",\n" +
	"\x13RevokeAPIKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"L\n" +
	"\x14RevokeAPIKeyResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\"g\n" +
	"\x13VerifyAPIKeyRequest\x12\x1d\n" +
	"\n" +
	"key_digest\x18\x01 \x01(\tR\tkeyDigest\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\"\xa0\x01\n" +
	"\x14VerifyAPIKeyResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.taas.common.v1.ResponseR\bresponse\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role2\xab\x05\n" +
	"\vAuthService\x12n\n" +
	"\n" +
	"CreateUser\x12\x1f.taas.auth.v1.CreateUserRequest\x1a .taas.auth.v1.CreateUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/users\x12_\n" +
	"\x05Login\x12\x1a.taas.auth.v1.LoginRequest\x1a\x1b.taas.auth.v1.LoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12q\n" +
	"\vListAPIKeys\x12 .taas.auth.v1.ListAPIKeysRequest\x1a!.taas.auth.v1.ListAPIKeysResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/auth/api-keys\x12w\n" +
	"\fCreateAPIKey\x12!.taas.auth.v1.CreateAPIKeyRequest\x1a\".taas.auth.v1.CreateAPIKeyResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/api-keys\x12\x87\x01\n" +
	"\fRevokeAPIKey\x12!.taas.auth.v1.RevokeAPIKeyRequest\x1a\".taas.auth.v1.RevokeAPIKeyResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/auth/api-keys/{key_id}:revoke\x12U\n" +
	"\fVerifyAPIKey\x12!.taas.auth.v1.VerifyAPIKeyRequest\x1a\".taas.auth.v1.VerifyAPIKeyResponseB\xa5\x01\n" +
	"\x10com.taas.auth.v1B\tAuthProtoP\x01Z4github.com/go-taas/go-taas/proto/taas/auth/v1;authv1\xa2\x02\x03TAX\xaa\x02\fTaas.Auth.V1\xca\x02\fTaas\\Auth\\V1\xe2\x02\x18Taas\\Auth\\V1\\GPBMetadata\xea\x02\x0eTaas::Auth::V1b\x06proto3"

var (
	file_taas_auth_v1_auth_proto_rawDescOnce sync.Once
	file_taas_auth_v1_auth_proto_rawDescData []byte
)

func file_taas_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_taas_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_taas_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taas_auth_v1_auth_proto_rawDesc), len(file_taas_auth_v1_auth_proto_rawDesc)))
	})
	return file_taas_auth_v1_auth_proto_rawDescData
}

var file_taas_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_taas_auth_v1_auth_proto_goTypes = []any{
	(*CreateUserRequest)(nil),    // 0: taas.auth.v1.CreateUserRequest
	(*CreateUserResponse)(nil),   // 1: taas.auth.v1.CreateUserResponse
	(*LoginRequest)(nil),         // 2: taas.auth.v1.LoginRequest
	(*LoginResponse)(nil),        // 3: taas.auth.v1.LoginResponse
	(*ListAPIKeysRequest)(nil),   // 4: taas.auth.v1.ListAPIKeysRequest
	(*ListAPIKeysResponse)(nil),  // 5: taas.auth.v1.ListAPIKeysResponse
	(*APIKeySummary)(nil),        // 6: taas.auth.v1.APIKeySummary
	(*CreateAPIKeyRequest)(nil),  // 7: taas.auth.v1.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil), // 8: taas.auth.v1.CreateAPIKeyResponse
	(*RevokeAPIKeyRequest)(nil),  // 9: taas.auth.v1.RevokeAPIKeyRequest
	(*RevokeAPIKeyResponse)(nil), // 10: taas.auth.v1.RevokeAPIKeyResponse
	(*VerifyAPIKeyRequest)(nil),  // 11: taas.auth.v1.VerifyAPIKeyRequest
	(*VerifyAPIKeyResponse)(nil), // 12: taas.auth.v1.VerifyAPIKeyResponse
	(*v1.Response)(nil),          // 13: taas.common.v1.Response
	(*v1.PageRequest)(nil),       // 14: taas.common.v1.PageRequest
	(*v1.PageMeta)(nil),          // 15: taas.common.v1.PageMeta
}
var file_taas_auth_v1_auth_proto_depIdxs = []int32{
	13, // 0: taas.auth.v1.CreateUserResponse.response:type_name -> taas.common.v1.Response
	13, // 1: taas.auth.v1.LoginResponse.response:type_name -> taas.common.v1.Response
	14, // 2: taas.auth.v1.ListAPIKeysRequest.page:type_name -> taas.common.v1.PageRequest
	13, // 3: taas.auth.v1.ListAPIKeysResponse.response:type_name -> taas.common.v1.Response
	6,  // 4: taas.auth.v1.ListAPIKeysResponse.keys:type_name -> taas.auth.v1.APIKeySummary
	15, // 5: taas.auth.v1.ListAPIKeysResponse.page_meta:type_name -> taas.common.v1.PageMeta
	13, // 6: taas.auth.v1.CreateAPIKeyResponse.response:type_name -> taas.common.v1.Response
	13, // 7: taas.auth.v1.RevokeAPIKeyResponse.response:type_name -> taas.common.v1.Response
	13, // 8: taas.auth.v1.VerifyAPIKeyResponse.response:type_name -> taas.common.v1.Response
	0,  // 9: taas.auth.v1.AuthService.CreateUser:input_type -> taas.auth.v1.CreateUserRequest
	2,  // 10: taas.auth.v1.AuthService.Login:input_type -> taas.auth.v1.LoginRequest
	4,  // 11: taas.auth.v1.AuthService.ListAPIKeys:input_type -> taas.auth.v1.ListAPIKeysRequest
	7,  // 12: taas.auth.v1.AuthService.CreateAPIKey:input_type -> taas.auth.v1.CreateAPIKeyRequest
	9,  // 13: taas.auth.v1.AuthService.RevokeAPIKey:input_type -> taas.auth.v1.RevokeAPIKeyRequest
	11, // 14: taas.auth.v1.AuthService.VerifyAPIKey:input_type -> taas.auth.v1.VerifyAPIKeyRequest
	1,  // 15: taas.auth.v1.AuthService.CreateUser:output_type -> taas.auth.v1.CreateUserResponse
	3,  // 16: taas.auth.v1.AuthService.Login:output_type -> taas.auth.v1.LoginResponse
	5,  // 17: taas.auth.v1.AuthService.ListAPIKeys:output_type -> taas.auth.v1.ListAPIKeysResponse
	8,  // 18: taas.auth.v1.AuthService.CreateAPIKey:output_type -> taas.auth.v1.CreateAPIKeyResponse
	10, // 19: taas.auth.v1.AuthService.RevokeAPIKey:output_type -> taas.auth.v1.RevokeAPIKeyResponse
	12, // 20: taas.auth.v1.AuthService.VerifyAPIKey:output_type -> taas.auth.v1.VerifyAPIKeyResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_taas_auth_v1_auth_proto_init() }
func file_taas_auth_v1_auth_proto_init() {
	if File_taas_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taas_auth_v1_auth_proto_rawDesc), len(file_taas_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taas_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_taas_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_taas_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_taas_auth_v1_auth_proto = out.File
	file_taas_auth_v1_auth_proto_goTypes = nil
	file_taas_auth_v1_auth_proto_depIdxs = nil
}
